// ============================================================
//  ALL GHARPAYY PG PROPERTIES — sourced from IQ data sheet
//  Covers: Koramangala, Bellandur, Marathahalli, Mahadevapura,
//          Nagawara/Manyata, Electronic City, Whitefield, HSR,
//          BTM, Jayanagar, JP Nagar, MG Road, Indiranagar
// ============================================================

export interface PGProperty {
  id: string;
  slug: string;
  name: string;
  gharpayy_name: string;
  area: string;
  locality: string;
  city: string;
  nearby_landmarks: string[];
  google_maps_url?: string;
  gender_preference: 'male' | 'female' | 'any';
  target_audience: 'students' | 'working' | 'both';
  property_type: 'premium' | 'mid' | 'budget';
  room_types: string[];
  min_rent: number;
  max_rent: number;
  meals_included: number;
  food_type: 'veg' | 'non-veg' | 'both' | 'self-cook';
  utilities_included: boolean;
  electricity_extra: boolean;
  amenities: string[];
  safety_features: string[];
  common_areas: string[];
  walking_distance_mins: string;
  accessibility: string[];
  noise_level: 'low' | 'medium' | 'high';
  security_deposit: string;
  minimum_stay: string;
  usp: string;
  no_curfew: boolean;
  manager_contact?: string;
  owner_contact?: string;
  group_name?: string;
  actual_pg_name?: string;
  is_verified: boolean;
  is_active: boolean;
  photos: string[];
  average_rating: number;
  total_reviews: number;
  highlights: string[];
  price_range: string;
  tier: string;
}

const STD_AMENITIES = [
  'WiFi', 'Laundry Area', 'Power Backup', 'Elevator', 'Water Purifier',
  'Fridge', 'Microwave', 'Housekeeping', 'Gym', 'Rooftop', 'Lounge', 'Pantry',
];
const STD_SAFETY = ['CCTV', 'Security Guard', 'Fire Extinguisher'];
const STD_COMMON = ['Lounge', 'Gym', 'Pantry', 'Rooftop'];

function pg(overrides: Partial<PGProperty> & Pick<PGProperty, 'id'|'slug'|'name'|'gharpayy_name'|'area'|'locality'|'nearby_landmarks'|'gender_preference'|'min_rent'|'max_rent'>): PGProperty {
  return {
    city: 'Bangalore',
    target_audience: 'both',
    property_type: 'mid',
    room_types: ['Single Sharing', 'Double Sharing'],
    meals_included: 3,
    food_type: 'both',
    utilities_included: true,
    electricity_extra: false,
    amenities: STD_AMENITIES,
    safety_features: STD_SAFETY,
    common_areas: STD_COMMON,
    walking_distance_mins: '10-15',
    accessibility: ['Bus'],
    noise_level: 'medium',
    security_deposit: 'One Month Rent',
    minimum_stay: '3 Months',
    usp: 'Budget friendly, games, coliving vibe, no curfew',
    no_curfew: true,
    is_verified: true,
    is_active: true,
    photos: [],
    average_rating: 4.7,
    total_reviews: 40,
    highlights: ['Meals Included', 'No Curfew', 'Fully Furnished'],
    price_range: '',
    tier: 'Mid',
    ...overrides,
  };
}

export const ALL_PROPERTIES: PGProperty[] = [

  // ─── KORAMANGALA ──────────────────────────────────────────────────────────
  pg({
    id: 'forum-pro-boys', slug: 'forum-pro-boys',
    name: 'Forum Pro Boys Koramangala', gharpayy_name: 'FORUM PRO BOYS',
    area: 'Koramangala', locality: 'Silk Board, SG Palya, Nexus Mall',
    nearby_landmarks: ['Nexus Mall', 'Christ University', 'Dairy Circle'],
    google_maps_url: 'https://maps.app.goo.gl/CDmFo9KYX3Ds7anv7',
    gender_preference: 'male',
    room_types: ['Single Sharing', 'Double Sharing', 'Triple Sharing'],
    min_rent: 13000, max_rent: 23000,
    price_range: 'T13K / D16K / S23K',
    meals_included: 4,
    food_type: 'veg',
    manager_contact: '8296124422',
    group_name: 'Kalpavriksha',
    actual_pg_name: 'Kalpavriksha',
    usp: 'Newly built, GYM, Games, No Curfew, 4 meals/day',
    highlights: ['Newly Built', 'Gym & Games', '4 Meals/Day', 'No Curfew'],
    tier: 'Mid',
  }),

  pg({
    id: 'forum-1-boys', slug: 'forum-1-boys',
    name: 'Forum 1 Boys Koramangala', gharpayy_name: 'FORUM 1 BOYS',
    area: 'Koramangala', locality: 'Silk Board, SG Palya, Nexus Mall',
    nearby_landmarks: ['Nexus Mall', 'Christ University', 'Dairy Circle'],
    google_maps_url: 'https://maps.app.goo.gl/CDmFo9KYX3Ds7anv7',
    gender_preference: 'male',
    room_types: ['Single Sharing', 'Double Sharing', 'Triple Sharing'],
    min_rent: 12000, max_rent: 24000,
    price_range: 'T10K / D14K / S21K',
    meals_included: 4,
    food_type: 'veg',
    manager_contact: '7275630428',
    group_name: 'Kalpavriksha',
    actual_pg_name: 'Kalpavriksha',
    usp: 'Newly built, GYM, Games, No Curfew, 4 meals/day',
    highlights: ['Newly Built', 'Gym & Games', '4 Meals/Day', 'No Curfew'],
    tier: 'Mid',
  }),

  pg({
    id: 'aira-boys', slug: 'aira-boys',
    name: 'Aira Boys Koramangala', gharpayy_name: 'AIRA BOYS',
    area: 'Koramangala', locality: 'SG Palya, Nexus Mall',
    nearby_landmarks: ['Nexus Mall', 'Christ University', 'Dairy Circle'],
    gender_preference: 'male',
    room_types: ['Single Sharing', 'Double Sharing'],
    min_rent: 15000, max_rent: 24000,
    price_range: 'D13K / S24K',
    meals_included: 4,
    food_type: 'veg',
    manager_contact: '9731750056',
    actual_pg_name: 'Airavati PG Your Shell',
    usp: 'Newly built, GYM, Games, No Curfew',
    highlights: ['4 Meals/Day', 'Gym', 'No Curfew', 'Premium Location'],
    tier: 'Mid',
  }),

  pg({
    id: 'wink-boys', slug: 'wink-boys',
    name: 'Wink Boys Koramangala', gharpayy_name: 'Wink Boys',
    area: 'Koramangala', locality: 'Adugodi, Tavrekere',
    nearby_landmarks: ['Nexus Mall', 'Christ University', 'Dairy Circle'],
    gender_preference: 'male',
    room_types: ['Single Sharing', 'Double Sharing'],
    min_rent: 12000, max_rent: 19000,
    price_range: 'D9.5K / S17K',
    meals_included: 4,
    food_type: 'veg',
    owner_contact: '9514130240',
    actual_pg_name: 'Purple Boys PG',
    usp: 'Very nearby to Christ, Fiserv, Accenture, Razorpay. Gym & Games',
    highlights: ['Near Christ University', '4 Meals/Day', 'Gym & Games', 'No Curfew'],
    tier: 'Mid',
  }),

  pg({
    id: 'grand-girly', slug: 'grand-girly',
    name: 'Grand Girly Koramangala', gharpayy_name: 'GRAND GIRLY',
    area: 'Koramangala', locality: 'SG Palya, Tavrekere',
    nearby_landmarks: ['Nexus Mall', 'Christ University', 'Dairy Circle'],
    gender_preference: 'female',
    room_types: ['Single Sharing', 'Double Sharing', 'Triple Sharing'],
    min_rent: 12000, max_rent: 25000,
    price_range: 'T10K / D14K / S25K',
    meals_included: 3,
    food_type: 'veg',
    usp: 'Nearby to Christ, Fiserv, Accenture, Razorpay. Games. No Curfew',
    highlights: ['Girls Only', 'Games Room', 'Prime Location', 'No Curfew'],
    tier: 'Mid',
  }),

  pg({
    id: 's-girly-rk', slug: 's-girly-rk',
    name: 'S Girly RK Koramangala', gharpayy_name: 'S GIRLY RK',
    area: 'Koramangala', locality: 'SG Palya, Tavrekere',
    nearby_landmarks: ['Nexus Mall', 'Christ University', 'Dairy Circle'],
    gender_preference: 'female',
    room_types: ['Single Sharing', 'Double Sharing'],
    min_rent: 14000, max_rent: 27000,
    price_range: 'D14K / S27K',
    meals_included: 3,
    food_type: 'veg',
    owner_contact: '8105580674',
    actual_pg_name: 'GG Affordable SG / Sri PMR PG for Ladies',
    usp: 'Nearby to Christ, Fiserv, Accenture, Razorpay. Games. No Curfew',
    highlights: ['Girls Only', 'Games Room', 'Prime Location', 'No Curfew'],
    tier: 'Mid',
  }),

  pg({
    id: 'zexus-boys', slug: 'zexus-boys',
    name: 'Zexus Boys Koramangala', gharpayy_name: 'Zexus Boys',
    area: 'Koramangala', locality: 'SG Palya, Nexus Mall',
    nearby_landmarks: ['Nexus Mall', 'Christ University', 'Dairy Circle'],
    gender_preference: 'male',
    room_types: ['Single Sharing', 'Double Sharing'],
    min_rent: 16000, max_rent: 27000,
    price_range: 'D16K(Non-AC) / D18K(AC) / S27K',
    electricity_extra: true,
    manager_contact: '8882037105',
    owner_contact: '9844027607',
    actual_pg_name: 'Gharpayy x Zexus Boys Your Space',
    usp: 'Premium, very nearby to Christ, Fiserv, Accenture, Razorpay. Gym & Games',
    property_type: 'premium',
    highlights: ['Premium', 'Near Christ', 'AC Available', 'No Curfew'],
    tier: 'Basic Plus',
  }),

  pg({
    id: 'nex-coed', slug: 'nex-coed',
    name: 'Nex Coed Koramangala', gharpayy_name: 'NEX COED',
    area: 'Koramangala', locality: 'SG Palya, Nexus Mall',
    nearby_landmarks: ['Nexus Mall', 'Christ University', 'Dairy Circle'],
    gender_preference: 'any',
    room_types: ['Single Sharing', 'Double Sharing', 'Triple Sharing'],
    min_rent: 13000, max_rent: 27000,
    price_range: 'T13K / D17K / S27K',
    electricity_extra: true,
    usp: 'Great property, Games, Very nearby to Christ, Fiserv, Accenture, Razorpay',
    highlights: ['Co-ed', 'Prime Location', 'Near Nexus Mall', 'No Curfew'],
    tier: 'Mid',
  }),

  pg({
    id: 'joy-girls', slug: 'joy-girls',
    name: 'Joy Girls Koramangala', gharpayy_name: 'JOY GIRLS',
    area: 'Koramangala', locality: 'Silk Board, SG Palya, Nexus Mall',
    nearby_landmarks: ['Nexus Mall', 'Christ University', 'Dairy Circle'],
    gender_preference: 'female',
    room_types: ['Single Sharing', 'Double Sharing', 'Triple Sharing'],
    min_rent: 12000, max_rent: 24000,
    price_range: 'T10K / D14K / S21K',
    manager_contact: '7353735588',
    owner_contact: '9110592795',
    actual_pg_name: 'Siri Paradise',
    usp: 'Newest PG, Prime Location, WFH Enabler, Good Food',
    highlights: ['Girls Only', 'Newest PG', 'Prime Location', 'No Curfew'],
    tier: 'Mid',
  }),

  pg({
    id: 'wyse-girls', slug: 'wyse-girls',
    name: 'Wyse Girls Koramangala', gharpayy_name: 'WYSE GIRLS',
    area: 'Koramangala', locality: 'Christ Central, IBC Knowledge Park',
    nearby_landmarks: ['Nexus Mall', 'Christ University', 'Dairy Circle'],
    gender_preference: 'female',
    noise_level: 'low',
    room_types: ['Single Sharing', 'Double Sharing'],
    min_rent: 19000, max_rent: 31000,
    price_range: 'D19K / S31K',
    usp: 'Flat setup, no curfew',
    highlights: ['Girls Only', 'Flat Setup', 'Low Noise', 'No Curfew'],
    tier: 'Basic Plus',
    average_rating: 4.8,
  }),

  pg({
    id: 'xold-flat-like', slug: 'xold-flat-like',
    name: 'Xold Flatlike Coed Koramangala', gharpayy_name: 'XOLD FLAT LIKE',
    area: 'Koramangala', locality: 'Silk Board, SG Palya, MG Road, Nexus',
    nearby_landmarks: ['Nexus Mall', 'Christ University', 'Dairy Circle'],
    gender_preference: 'any',
    noise_level: 'low',
    room_types: ['Single Sharing', 'Double Sharing', 'Triple Sharing'],
    min_rent: 11000, max_rent: 24000,
    price_range: 'T11K / D15K / S24K',
    meals_included: 4,
    food_type: 'veg',
    manager_contact: '9870227819',
    actual_pg_name: 'Lotus / Puzzles - Stellar House',
    usp: 'Flat type setup with sofa, fridge, TV. 2W parking. Daily cleaning',
    highlights: ['Flat-Like Setup', 'Daily Cleaning', '4 Meals/Day', 'No Curfew'],
    tier: 'Mid',
  }),

  pg({
    id: 'roar-coed', slug: 'roar-coed',
    name: 'Roar Colive Koramangala', gharpayy_name: 'Roar Colive',
    area: 'Koramangala', locality: 'IBC Knowledge Park, Dairy Circle',
    nearby_landmarks: ['Nexus Mall', 'Christ University', 'IBC Knowledge Park'],
    gender_preference: 'any',
    room_types: ['Single Sharing', 'Double Sharing'],
    min_rent: 13000, max_rent: 24000,
    price_range: 'D13K / S24K',
    meals_included: 4,
    food_type: 'veg',
    manager_contact: '9721538096',
    owner_contact: '9600530780',
    actual_pg_name: 'SLV Luxury Coliving PG',
    usp: 'Coliving stay - rarely available. Best & big rooms. Great food',
    highlights: ['Coliving', 'Big Rooms', 'Great Food', 'No Curfew'],
    tier: 'Mid',
  }),

  pg({
    id: 'sg-colive', slug: 'sg-colive',
    name: 'SG Coliving Koramangala', gharpayy_name: 'SG COLIVE',
    area: 'Koramangala', locality: 'IBC Knowledge, Baneraghata, Dairy Circle',
    nearby_landmarks: ['Nexus Mall', 'Christ University', 'Dairy Circle'],
    gender_preference: 'any',
    noise_level: 'low',
    room_types: ['Single Sharing', 'Double Sharing', 'Triple Sharing'],
    min_rent: 9000, max_rent: 23000,
    price_range: 'T8.5K / D12K / S22K',
    manager_contact: '6205229187',
    owner_contact: '7598844465',
    actual_pg_name: 'Nesto Amigo SG',
    usp: 'Extremely budget friendly, mini gym & games, coliving',
    highlights: ['Budget Friendly', 'Gym & Games', 'Coliving', 'No Curfew'],
    tier: 'Mid',
  }),

  pg({
    id: 'gt-girls', slug: 'gt-girls',
    name: 'GT Girls Koramangala', gharpayy_name: 'GT GIRLS',
    area: 'Koramangala', locality: 'Silk Board, SG Palya, MG Road',
    nearby_landmarks: ['Nexus Mall', 'Christ University', 'IBC Knowledge Park'],
    gender_preference: 'female',
    noise_level: 'low',
    room_types: ['Single Sharing', 'Double Sharing'],
    min_rent: 15000, max_rent: 26000,
    price_range: 'D15K / S26K',
    meals_included: 4,
    food_type: 'veg',
    actual_pg_name: 'My Roomie Lavender',
    usp: 'Best girls property in Koramangala. Newly built, GYM, Games',
    highlights: ['Best Girls PG Koramangala', 'Newly Built', 'Gym', 'No Curfew'],
    tier: 'Mid',
    average_rating: 4.9,
  }),

  pg({
    id: 'orange-capital', slug: 'orange-capital',
    name: 'Orange Capital Girls Koramangala', gharpayy_name: 'Orange Captial',
    area: 'Koramangala', locality: 'Hosur Road',
    nearby_landmarks: ['Nexus Mall', 'Christ University', 'IBC Knowledge Park'],
    gender_preference: 'female',
    room_types: ['Single Sharing', 'Double Sharing'],
    min_rent: 13000, max_rent: 20000,
    price_range: 'D12K / S19K',
    manager_contact: '8050509559',
    actual_pg_name: 'Adler near Pink Cap',
    usp: 'Prime location, big rooms, good food',
    highlights: ['Girls Only', 'Big Rooms', 'Good Food', 'No Curfew'],
    tier: 'Mid',
  }),

  pg({
    id: 'fab-girls', slug: 'fab-girls',
    name: 'Fab Girls Koramangala', gharpayy_name: 'Fab Girls',
    area: 'Koramangala', locality: 'Hosur Road',
    nearby_landmarks: ['Nexus Mall', 'Christ University', 'Dairy Circle'],
    gender_preference: 'female',
    noise_level: 'low',
    room_types: ['Single Sharing', 'Double Sharing', 'Triple Sharing'],
    min_rent: 10000, max_rent: 23000,
    price_range: 'T9K / D11K / S22K',
    manager_contact: '8296728581',
    actual_pg_name: 'Adler near ACE',
    usp: '400m from Christ Central Backgate',
    highlights: ['Girls Only', 'Near Christ', 'Budget Friendly', 'No Curfew'],
    tier: 'Mid',
  }),

  pg({
    id: 'quin-girls', slug: 'quin-girls',
    name: 'Quin Girls Koramangala', gharpayy_name: 'Quin GIRL KS',
    area: 'Koramangala', locality: 'IBC Knowledge, Baneraghata',
    nearby_landmarks: ['Nexus Mall', 'Christ University', 'Dairy Circle'],
    gender_preference: 'female',
    room_types: ['Single Sharing', 'Double Sharing'],
    min_rent: 15000, max_rent: 25000,
    price_range: 'D15K / S25K',
    meals_included: 4,
    actual_pg_name: 'Class House',
    usp: 'Super close to everything, common area, good PG food, next to mall',
    highlights: ['Girls Only', 'Near Mall', '4 Meals/Day', 'No Curfew'],
    tier: 'Mid',
  }),

  pg({
    id: 'homy-girls', slug: 'homy-girls',
    name: 'Homy Girls Koramangala', gharpayy_name: 'HOMY GIRLS',
    area: 'Koramangala', locality: 'Silk Board, SG Palya, MG Road',
    nearby_landmarks: ['Nexus Mall', 'Christ University', 'Dairy Circle'],
    gender_preference: 'female',
    room_types: ['Single Sharing', 'Double Sharing'],
    min_rent: 19000, max_rent: 28000,
    price_range: 'D19K / S28K',
    meals_included: 4,
    manager_contact: '6363722172',
    actual_pg_name: 'Nook Astella',
    usp: 'Great property, newly, GYM, Games',
    highlights: ['Girls Only', 'Gym & Games', 'Near Christ', 'No Curfew'],
    tier: 'Mid',
  }),

  pg({
    id: 'tom-boys-k', slug: 'tom-boys-k',
    name: 'Tom Boys Koramangala', gharpayy_name: 'Tom boys',
    area: 'Koramangala', locality: 'Silk Board, SG Palya, MG Road',
    nearby_landmarks: ['Nexus Mall', 'Christ University', 'Dairy Circle'],
    gender_preference: 'male',
    room_types: ['Single Sharing', 'Double Sharing', 'Triple Sharing'],
    min_rent: 12000, max_rent: 24000,
    price_range: 'T12K / D15K / S23K',
    meals_included: 4,
    manager_contact: '7204036862',
    group_name: 'KLP',
    actual_pg_name: 'KLP 5 Old',
    usp: 'Super close to everything, gym area, best PG food',
    highlights: ['Best PG Food', 'Gym', 'Near Everything', 'No Curfew'],
    tier: 'Mid',
  }),

  pg({
    id: 'snook-coed', slug: 'snook-coed',
    name: 'Snook Coed Koramangala', gharpayy_name: 'SNOOK COED',
    area: 'Koramangala', locality: 'IBC Knowledge, Dairy Circle',
    nearby_landmarks: ['Nexus Mall', 'Christ University', 'IBC Knowledge Park'],
    gender_preference: 'any',
    room_types: ['Single Sharing', 'Double Sharing', 'Triple Sharing'],
    min_rent: 11000, max_rent: 23000,
    price_range: 'T11K / D14K / S22K',
    meals_included: 4,
    manager_contact: '8310877020',
    owner_contact: '9487626144',
    actual_pg_name: 'Yes Living',
    usp: 'Extremely budget friendly, mini gym & games, coliving',
    highlights: ['Co-ed', 'Budget Friendly', 'Gym & Games', 'No Curfew'],
    tier: 'Mid',
  }),

  pg({
    id: 'tavz-coed', slug: 'tavz-coed',
    name: 'Tavz Coed Koramangala', gharpayy_name: 'TAVZ COED',
    area: 'Koramangala', locality: 'Tavrekere',
    nearby_landmarks: ['Nexus Mall', 'Christ University', 'IBC Knowledge Park'],
    gender_preference: 'any',
    room_types: ['Single Sharing', 'Double Sharing', 'Triple Sharing'],
    min_rent: 9000, max_rent: 17000,
    price_range: 'D9K / S16K',
    google_maps_url: 'https://maps.app.goo.gl/3kV2t1AHyoTL9yTv7',
    manager_contact: '7353735588',
    actual_pg_name: 'Royal Paradise 1',
    usp: 'Coliving stay / affordable. No curfew',
    highlights: ['Most Affordable', 'Coliving', 'No Curfew', 'Games'],
    tier: 'Mid',
  }),

  pg({
    id: 'pink-capital', slug: 'pink-capital',
    name: 'Pink Capital Girls Koramangala', gharpayy_name: 'Pink capital',
    area: 'Koramangala', locality: 'Hosur Road',
    nearby_landmarks: ['Nexus Mall', 'Christ University', 'IBC Knowledge Park'],
    gender_preference: 'female',
    room_types: ['Single Sharing', 'Double Sharing'],
    min_rent: 13000, max_rent: 27000,
    price_range: 'D13K / S18K / Premium S27K',
    manager_contact: '9611728757',
    owner_contact: '7892131987',
    actual_pg_name: '73 House of Zisk',
    usp: 'Pink & new interiors, prime location',
    highlights: ['Girls Only', 'Pink Interiors', 'Prime Location', 'No Curfew'],
    tier: 'Mid',
  }),

  pg({
    id: 'khb-girls', slug: 'khb-girls',
    name: 'KHB Girls Koramangala', gharpayy_name: 'khb girls',
    area: 'Koramangala', locality: '8th Block Koramangala, HSR',
    nearby_landmarks: ['Nexus Mall', 'Christ University', 'IBC Knowledge Park'],
    gender_preference: 'female',
    room_types: ['Single Sharing', 'Double Sharing', 'Triple Sharing'],
    min_rent: 11000, max_rent: 24000,
    price_range: 'T11K / D13K / S24K',
    manager_contact: '9160689366',
    actual_pg_name: 'Nirvana',
    usp: 'Newly built, pocket friendly',
    highlights: ['Girls Only', 'Budget Friendly', 'Newly Built', 'No Curfew'],
    tier: 'Mid',
  }),

  pg({
    id: 'john-boys', slug: 'john-boys',
    name: 'John Boys Koramangala', gharpayy_name: 'John Boys',
    area: 'Koramangala', locality: 'Silk Board, SG Palya, MG Road',
    nearby_landmarks: ['Nexus Mall', 'Christ University', 'IBC Knowledge Park'],
    gender_preference: 'male',
    room_types: ['Single Sharing', 'Double Sharing', 'Triple Sharing'],
    min_rent: 9000, max_rent: 19000,
    price_range: 'T8K / D11K / S18K',
    manager_contact: '9440002382',
    owner_contact: '8374243567',
    actual_pg_name: 'RR PG',
    usp: 'Newest PG, Prime Location, WFH Enabler, Good Food',
    highlights: ['Budget Friendly', 'Prime Location', 'Good Food', 'No Curfew'],
    tier: 'Mid',
  }),

  pg({
    id: 'jack-coed', slug: 'jack-coed',
    name: 'Jack Coed Koramangala', gharpayy_name: 'jack coed',
    area: 'Koramangala', locality: 'SG Palya, MG Road, Nexus',
    nearby_landmarks: ['Nexus Mall', 'Christ University', 'IBC Knowledge Park'],
    gender_preference: 'any',
    room_types: ['Double Sharing', 'Triple Sharing'],
    min_rent: 15000, max_rent: 25000,
    price_range: 'D16K / T15K',
    meals_included: 4,
    manager_contact: '8951598703',
    actual_pg_name: 'Euphoria (Class Building)',
    usp: 'Best PG, super big almirah, wakefit mattress, snooker, chess, carrom',
    highlights: ['Games Room', 'Wakefit Mattress', 'Snooker & Chess', 'No Curfew'],
    tier: 'Mid',
  }),

  pg({
    id: 'gforum-girls', slug: 'gforum-girls',
    name: 'Forum Girls Koramangala', gharpayy_name: 'G Forum GIRLS',
    area: 'Koramangala', locality: 'IBC Knowledge, Dairy Circle',
    nearby_landmarks: ['Nexus Mall', 'Christ University', 'IBC Knowledge Park'],
    gender_preference: 'female',
    room_types: ['Single Sharing', 'Double Sharing'],
    min_rent: 14000, max_rent: 22000,
    price_range: 'D13K / S22K',
    meals_included: 4,
    manager_contact: '8800887053',
    owner_contact: '9606631307',
    actual_pg_name: 'Class House',
    usp: 'Super close to everything, common area, good PG food, next to mall',
    highlights: ['Girls Only', 'Near Mall', '4 Meals/Day', 'No Curfew'],
    tier: 'Mid',
  }),

  pg({
    id: 'homely-boys', slug: 'homely-boys',
    name: 'Homely Boys Koramangala', gharpayy_name: 'Homely BOYS',
    area: 'Koramangala', locality: 'Silk Board, SG Palya, MG Road',
    nearby_landmarks: ['Nexus Mall', 'Christ University', 'IBC Knowledge Park'],
    gender_preference: 'male',
    room_types: ['Single Sharing', 'Double Sharing', 'Triple Sharing'],
    min_rent: 14000, max_rent: 24000,
    price_range: 'T14K / D17K / S24K',
    meals_included: 4,
    manager_contact: '6364800803',
    group_name: 'KLP',
    actual_pg_name: 'Kalpavriksha',
    usp: 'Newly built, GYM, Games. No Curfew',
    highlights: ['Boys Only', 'Gym & Games', 'Newly Built', 'No Curfew'],
    tier: 'Mid',
  }),

  pg({
    id: 'homely-girls', slug: 'homely-girls',
    name: 'Homely Girls Koramangala', gharpayy_name: 'Homely GIRLS',
    area: 'Koramangala', locality: 'Silk Board, SG Palya, MG Road',
    nearby_landmarks: ['Nexus Mall', 'Christ University', 'IBC Knowledge Park'],
    gender_preference: 'female',
    room_types: ['Single Sharing', 'Double Sharing', 'Triple Sharing'],
    min_rent: 14000, max_rent: 24000,
    price_range: 'T14K / D17K / S24K',
    meals_included: 4,
    manager_contact: '6364800803',
    group_name: 'KLP',
    actual_pg_name: 'Kalpavriksha 1 Girls',
    usp: 'Newly built, GYM, Games, library. No Curfew',
    highlights: ['Girls Only', 'Gym & Library', 'Newly Built', 'No Curfew'],
    tier: 'Mid',
    average_rating: 4.9,
  }),

  pg({
    id: 'affo-girls-nv', slug: 'affo-girls-nv',
    name: 'Affo Girls Koramangala', gharpayy_name: 'AFFO GIRLS NV',
    area: 'Koramangala', locality: 'IBC Knowledge, Dairy Circle',
    nearby_landmarks: ['Nexus Mall', 'Christ University', 'IBC Knowledge Park'],
    gender_preference: 'female',
    room_types: ['Single Sharing', 'Double Sharing'],
    min_rent: 11000, max_rent: 22000,
    price_range: 'D11K / S20K',
    meals_included: 4,
    food_type: 'both',
    manager_contact: '9032867594',
    owner_contact: '7892014576',
    actual_pg_name: 'GG Madhavi Homes CL Layout / Class House',
    usp: 'Super close to everything, common area, good PG food, next to mall',
    highlights: ['Girls Only', 'Non-Veg Food', 'Near Mall', 'No Curfew'],
    tier: 'Mid',
  }),

  pg({
    id: 'gq-girls', slug: 'gq-girls',
    name: 'GQ Girls Koramangala', gharpayy_name: 'GQ girl',
    area: 'Koramangala', locality: 'Nexus, IBC Knowledge, Dairy Circle',
    nearby_landmarks: ['Nexus Mall', 'Christ University', 'IBC Knowledge Park'],
    gender_preference: 'female',
    room_types: ['Single Sharing', 'Double Sharing'],
    min_rent: 17000, max_rent: 25000,
    price_range: 'D17K / S25K',
    meals_included: 4,
    manager_contact: '8884449621',
    actual_pg_name: 'My Home Grandeur',
    usp: 'Super close to everything, common area, good PG food, next to mall',
    highlights: ['Girls Only', 'Near Mall', '4 Meals/Day', 'No Curfew'],
    tier: 'Mid',
  }),

  pg({
    id: 'esplanade-girls', slug: 'esplanade-girls',
    name: 'Esplanade Girls Koramangala', gharpayy_name: 'ESPLANADE GIRLS',
    area: 'Koramangala', locality: 'Silk Board, SG Palya, MG Road',
    nearby_landmarks: ['Nexus Mall', 'Christ University', 'IBC Knowledge Park'],
    gender_preference: 'female',
    property_type: 'budget',
    room_types: ['Single Sharing', 'Double Sharing', 'Triple Sharing'],
    min_rent: 21000, max_rent: 41000,
    price_range: 'T21K / D24K / D-AC28K / S37K / S-AC41K',
    meals_included: 4,
    manager_contact: '6364800803',
    group_name: 'KLP',
    actual_pg_name: 'Kalpavriksha Gardenia',
    usp: 'Best girls property in Koramangala. Newly built, GYM, Games',
    highlights: ['Girls Only', 'Premium', 'AC Available', 'No Curfew'],
    tier: 'Classics',
  }),

  pg({
    id: 'ace-girls', slug: 'ace-girls',
    name: 'ACE Girls Koramangala', gharpayy_name: 'Ace Girls',
    area: 'Koramangala', locality: 'Madiwala, SG Palya, Dairy Circle',
    nearby_landmarks: ['Nexus Mall', 'Christ University', 'Dairy Circle'],
    gender_preference: 'female',
    room_types: ['Single Sharing', 'Double Sharing'],
    min_rent: 23000, max_rent: 27000,
    price_range: 'D23K / D-AC25K',
    meals_included: 4,
    food_type: 'veg',
    manager_contact: '7619210662',
    owner_contact: '9606333530',
    actual_pg_name: 'Puzzles Living Grandeur House',
    usp: 'Best PG, super big almirah, wakefit mattress, snooker, chess, carrom',
    highlights: ['Girls Only', 'Premium', 'Games & Snooker', 'No Curfew'],
    tier: 'Classics',
    average_rating: 4.9,
    property_type: 'premium',
  }),

  pg({
    id: 'mvs-pearls', slug: 'mvs-pearls',
    name: 'MVS Pearls Coed Koramangala', gharpayy_name: 'MVS PEARLS',
    area: 'Koramangala', locality: 'Silk Board, SG Palya',
    nearby_landmarks: ['Nexus Mall', 'Christ University', 'Dairy Circle'],
    gender_preference: 'any',
    room_types: ['Single Sharing', 'Double Sharing'],
    min_rent: 15000, max_rent: 23000,
    price_range: 'D15K / S23K',
    meals_included: 4,
    manager_contact: '7022914317',
    owner_contact: '9535200009',
    actual_pg_name: 'DC Gardenia',
    usp: 'Premium flat-like setup',
    highlights: ['Co-ed', 'Flat-Like Setup', '4 Meals/Day', 'No Curfew'],
    tier: 'Mid',
  }),

  pg({
    id: 'korve-coed', slug: 'korve-coed',
    name: 'Korve Coed Koramangala', gharpayy_name: 'KORVE COED',
    area: 'Koramangala', locality: 'Koramangala',
    nearby_landmarks: ['Nexus Mall', 'Christ University', 'Dairy Circle'],
    gender_preference: 'any',
    property_type: 'premium',
    room_types: ['Single Sharing', 'Double Sharing'],
    min_rent: 18000, max_rent: 35000,
    price_range: 'D18K / D-Premium22K / S28K / S-Premium35K',
    manager_contact: '8139991234',
    owner_contact: '9701848769',
    actual_pg_name: 'Nextt Door',
    usp: 'Premium property',
    highlights: ['Co-ed', 'Premium', 'Near Everything', 'No Curfew'],
    tier: 'Classics',
    average_rating: 4.8,
  }),

  pg({
    id: 'zexx-coed', slug: 'zexx-coed',
    name: 'Zexx Coed Koramangala', gharpayy_name: 'zexx coed',
    area: 'Koramangala', locality: 'SG Palya',
    nearby_landmarks: ['Nexus Mall', 'Christ University', 'Dairy Circle'],
    gender_preference: 'any',
    noise_level: 'low',
    room_types: ['Single Sharing', 'Double Sharing'],
    min_rent: 13000, max_rent: 20000,
    price_range: 'D12K / S18K',
    manager_contact: '8867972551',
    owner_contact: '8951142499',
    actual_pg_name: 'Mojo Princeton',
    usp: 'Budget friendly, no curfew',
    highlights: ['Co-ed', 'Budget Friendly', 'Gym', 'No Curfew'],
    tier: 'Mid',
  }),

  pg({
    id: 'qut-girls', slug: 'qut-girls',
    name: 'QUT Girls Koramangala', gharpayy_name: 'QUT GIRLS',
    area: 'Koramangala', locality: 'SG Palya',
    nearby_landmarks: ['Nexus Mall', 'Christ University', 'Dairy Circle'],
    gender_preference: 'female',
    room_types: ['Single Sharing', 'Double Sharing', 'Triple Sharing'],
    min_rent: 11000, max_rent: 20000,
    price_range: 'T10K / D12K / S18K',
    manager_contact: '8792915685',
    actual_pg_name: 'Mojo Harwad House',
    usp: 'Budget friendly rooms, surrounded with restaurants',
    highlights: ['Girls Only', 'Budget Friendly', 'Near Restaurants', 'No Curfew'],
    tier: 'Mid',
  }),

  pg({
    id: 'koravill-girls', slug: 'koravill-girls',
    name: 'Koravill Girls Koramangala', gharpayy_name: 'KORAVILL GIRLS',
    area: 'Koramangala', locality: 'Ejipura, Koramangala',
    nearby_landmarks: ['Nexus Mall', 'Christ University', 'Dairy Circle'],
    gender_preference: 'female',
    property_type: 'budget',
    room_types: ['Single Sharing', 'Double Sharing', 'Triple Sharing'],
    min_rent: 11000, max_rent: 22000,
    price_range: 'T8K / D11K / S20K',
    manager_contact: '8310714410',
    actual_pg_name: 'Monika Ladies PG',
    usp: '2 min from landmark',
    noise_level: 'low',
    highlights: ['Girls Only', 'Budget', '2 Min Walk', 'No Curfew'],
    tier: 'Budget',
  }),

  // ─── BTM LAYOUT ──────────────────────────────────────────────────────────
  pg({
    id: 'btm-coed', slug: 'btm-coed',
    name: 'BTM Layout Coed', gharpayy_name: 'BTM Layout',
    area: 'BTM Layout', locality: 'Silk Board, BTM',
    nearby_landmarks: ['Silk Board Metro', 'BTM Layout'],
    gender_preference: 'any',
    room_types: ['Single Sharing', 'Double Sharing'],
    min_rent: 11000, max_rent: 22000,
    price_range: 'D11K / S22K',
    highlights: ['Co-ed', 'Near Metro', 'Budget Friendly', 'No Curfew'],
    tier: 'Mid',
  }),

  pg({
    id: 'silq-coed', slug: 'silq-coed',
    name: 'Silq Coed BTM Layout', gharpayy_name: 'Silq coed',
    area: 'BTM Layout', locality: 'Madiwala, Tavrekere, SG Palya',
    nearby_landmarks: ['Silk Board', 'BTM Layout'],
    gender_preference: 'any',
    noise_level: 'low',
    room_types: ['Single Sharing', 'Double Sharing'],
    min_rent: 13000, max_rent: 22000,
    price_range: 'D13K / S22K',
    actual_pg_name: 'Royal White House Coliving',
    usp: 'Extremely budget friendly, mini gym & games, coliving',
    highlights: ['Co-ed', 'Budget Friendly', 'Gym & Games', 'No Curfew'],
    tier: 'Mid',
  }),

  pg({
    id: 'stm-coed', slug: 'stm-coed',
    name: 'STM Coed Silk Board/BTM', gharpayy_name: 'STM COED',
    area: 'BTM Layout', locality: 'Silk Board',
    nearby_landmarks: ['Silk Board Metro'],
    google_maps_url: 'https://maps.app.goo.gl/fMvhD5Sd3ayi4F47A',
    gender_preference: 'any',
    room_types: ['Single Sharing', 'Double Sharing'],
    min_rent: 13000, max_rent: 23000,
    price_range: 'D13K / S23K',
    manager_contact: '8187010212',
    actual_pg_name: 'SLC Royal Co-live',
    accessibility: ['Metro', 'Bus'],
    usp: 'Great property, games, very nearby to offices',
    highlights: ['Co-ed', 'Near Metro', 'Coliving', 'No Curfew'],
    tier: 'Mid',
  }),

  pg({
    id: 'lukas-coed', slug: 'lukas-coed',
    name: 'Lukas Coed BTM Layout', gharpayy_name: 'LUKAS COED',
    area: 'BTM Layout', locality: 'BTM Layout',
    nearby_landmarks: ['Silk Board Metro', 'BTM Layout'],
    gender_preference: 'any',
    noise_level: 'low',
    room_types: ['Single Sharing', 'Double Sharing'],
    min_rent: 12000, max_rent: 22000,
    price_range: 'D12K / S22K',
    manager_contact: '7893037059',
    actual_pg_name: 'Royal Suit House',
    usp: 'Good area, near to metro',
    highlights: ['Co-ed', 'Near Metro', 'Budget Friendly', 'No Curfew'],
    tier: 'Mid',
  }),

  pg({
    id: 'fable-girls', slug: 'fable-girls',
    name: 'Fable Girls BTM Layout', gharpayy_name: 'FABLE GIRLS',
    area: 'BTM Layout', locality: 'Silk Board, Near Metro',
    nearby_landmarks: ['Silk Board Metro', 'BTM Layout'],
    gender_preference: 'female',
    room_types: ['Single Sharing', 'Double Sharing', 'Triple Sharing'],
    min_rent: 10000, max_rent: 26000,
    price_range: 'T10K / D13K / S25K',
    manager_contact: '8431426795',
    owner_contact: '9980889487',
    actual_pg_name: 'GMB Comforts',
    usp: 'Good furnished property',
    highlights: ['Girls Only', 'Near Metro', 'Budget Friendly', 'No Curfew'],
    tier: 'Mid',
  }),

  pg({
    id: 'gg-bubblo-girls', slug: 'gg-bubblo-girls',
    name: 'GG Bubblo Girls SG Palya', gharpayy_name: 'GG BUBBLO GIRLS',
    area: 'BTM Layout', locality: 'SG Palya, Tavrekere',
    nearby_landmarks: ['Nexus Mall', 'Christ University', 'Dairy Circle'],
    gender_preference: 'female',
    noise_level: 'low',
    room_types: ['Single Sharing', 'Double Sharing'],
    min_rent: 13000, max_rent: 21000,
    price_range: 'D13K / S21K',
    actual_pg_name: 'Gyathri PG',
    usp: 'Extremely budget friendly, mini gym & games, coliving',
    highlights: ['Girls Only', 'Budget Friendly', 'Gym & Games', 'No Curfew'],
    tier: 'Mid',
  }),

  // ─── BELLANDUR ───────────────────────────────────────────────────────────
  pg({
    id: 'knox-coed', slug: 'knox-coed',
    name: 'Knox Coed Bellandur', gharpayy_name: 'KNOX COED',
    area: 'Bellandur', locality: 'Kadubeesanahalli',
    nearby_landmarks: ['Sony Software India', 'Embassy Tech Village'],
    google_maps_url: 'https://maps.app.goo.gl/adWbc5Z28ixXXGyr7',
    gender_preference: 'any',
    property_type: 'budget',
    room_types: ['Single Sharing', 'Double Sharing'],
    min_rent: 13000, max_rent: 23000,
    price_range: 'D11K / S21K',
    manager_contact: '7337777916',
    actual_pg_name: 'IVA Coliving',
    accessibility: ['Bus'],
    usp: 'Extremely budget friendly, mini gym & games. No curfew',
    highlights: ['Co-ed', 'Budget', 'Near Embassy Tech', 'No Curfew'],
    tier: 'Budget',
  }),

  pg({
    id: 'bell-coed', slug: 'bell-coed',
    name: 'Bell Coed Bellandur', gharpayy_name: 'BELL COED',
    area: 'Bellandur', locality: 'Bellandur',
    nearby_landmarks: ['Ecoworld', 'Flipkart', 'ETV'],
    google_maps_url: 'https://maps.app.goo.gl/GcoEbrkPuJVseYCC8',
    gender_preference: 'any',
    room_types: ['Single Sharing', 'Double Sharing', 'Triple Sharing'],
    min_rent: 11000, max_rent: 24000,
    price_range: 'T9K / D13K / S21K',
    manager_contact: '9110664880',
    owner_contact: '9108895879',
    actual_pg_name: 'Adler Bellandur',
    usp: 'Peak location, newly built with love, pocket friendly',
    highlights: ['Co-ed', 'Near Ecoworld', 'Budget Friendly', 'No Curfew'],
    tier: 'Mid',
  }),

  pg({
    id: 'treo-coed', slug: 'treo-coed',
    name: 'Treo Coed Bellandur', gharpayy_name: 'TREO COED',
    area: 'Bellandur', locality: 'Bellandur',
    nearby_landmarks: ['Ecoworld', 'Flipkart', 'ETV'],
    google_maps_url: 'https://maps.app.goo.gl/98XHhQYXgfkbj1Hd9',
    gender_preference: 'any',
    room_types: ['Single Sharing', 'Double Sharing'],
    min_rent: 12000, max_rent: 21000,
    price_range: 'D10K / S19K',
    owner_contact: '8639188095',
    actual_pg_name: 'Sri Srinivasa Comfort Co-Living PG',
    usp: 'Newest PG, Prime Location, WFH Enabler, Good Food',
    highlights: ['Co-ed', 'Newest PG', 'WFH Enabler', 'No Curfew'],
    tier: 'Mid',
  }),

  pg({
    id: 'zillion-coed', slug: 'zillion-coed',
    name: 'Zillion Coed Bellandur', gharpayy_name: 'ZILLION COED',
    area: 'Bellandur', locality: 'Ecoworld, Bellandur, ETV',
    nearby_landmarks: ['Ecoworld', 'Flipkart'],
    google_maps_url: 'https://maps.app.goo.gl/vqxjy8YQzH9H9DAZA',
    gender_preference: 'any',
    room_types: ['Single Sharing', 'Double Sharing'],
    min_rent: 15000, max_rent: 25000,
    price_range: 'D15K / S25K',
    manager_contact: '7996679991',
    owner_contact: '9739997392',
    actual_pg_name: 'Fab Inn by Echo Coliving',
    usp: 'Newest PG, Prime Location, WFH Enabler, Food Good',
    highlights: ['Newest PG', 'Prime Location', 'WFH Enabler', 'No Curfew'],
    tier: 'Mid',
  }),

  pg({
    id: 'phantom-coed', slug: 'phantom-coed',
    name: 'Phantom Coed Bellandur', gharpayy_name: 'PHANTOM COED',
    area: 'Bellandur', locality: 'Ecoworld, Bellandur, ETV',
    nearby_landmarks: ['Ecoworld', 'ETV'],
    google_maps_url: 'https://maps.app.goo.gl/dNUpaeppQgt3U2jDA',
    gender_preference: 'any',
    room_types: ['Single Sharing', 'Double Sharing'],
    min_rent: 15000, max_rent: 25000,
    price_range: 'D15K / S25K',
    manager_contact: '9133743622',
    actual_pg_name: 'Eden Premium Coliving',
    usp: 'New PG, Prime Location, Private TV, Food Good',
    highlights: ['Private TV', 'New PG', 'Prime Location', 'No Curfew'],
    tier: 'Mid',
  }),

  pg({
    id: 'zelite-coed', slug: 'zelite-coed',
    name: 'Zelite Coed Bellandur', gharpayy_name: 'ZELITE COED',
    area: 'Bellandur', locality: 'Ecoworld, Bellandur, ETV',
    nearby_landmarks: ['Ecoworld', 'ETV'],
    google_maps_url: 'https://maps.app.goo.gl/eKvChsGkhj81mWV76',
    gender_preference: 'any',
    room_types: ['Single Sharing', 'Double Sharing'],
    min_rent: 16000, max_rent: 28000,
    price_range: 'D16K / S28K',
    manager_contact: '7829501828',
    owner_contact: '8688066287',
    actual_pg_name: 'Jyotis Homestay Studio Rooms',
    usp: 'Peak location, newly built with love, pocket friendly',
    highlights: ['Co-ed', 'Studio Rooms', 'Near Ecoworld', 'No Curfew'],
    tier: 'Mid',
  }),

  pg({
    id: 'stanny-coed', slug: 'stanny-coed',
    name: 'Stanny Coed Bellandur', gharpayy_name: 'STANNY COED',
    area: 'Bellandur', locality: 'Bellandur, HSR',
    nearby_landmarks: ['Ecoworld', 'Flipkart', 'ETV'],
    google_maps_url: 'https://maps.app.goo.gl/2fhoVN2NYcy9jjCH8',
    gender_preference: 'any',
    room_types: ['Single Sharing', 'Double Sharing'],
    min_rent: 13000, max_rent: 24000,
    price_range: 'D12K / S23K',
    owner_contact: '7204019777',
    actual_pg_name: 'Stanley Coed',
    usp: 'Peak location, newly built with love, pocket friendly',
    highlights: ['Co-ed', 'Near Ecoworld', 'Pocket Friendly', 'No Curfew'],
    tier: 'Mid',
  }),

  pg({
    id: 'glen-coed', slug: 'glen-coed',
    name: 'Glen Coed Bellandur', gharpayy_name: 'GLEN COED',
    area: 'Bellandur', locality: 'Bellandur, HSR',
    nearby_landmarks: ['Ecoworld', 'ETV'],
    google_maps_url: 'https://maps.app.goo.gl/oHtiM3ofZQiRGnQY6',
    gender_preference: 'any',
    room_types: ['Single Sharing', 'Double Sharing'],
    min_rent: 11000, max_rent: 23000,
    price_range: 'D11K / S21K',
    owner_contact: '7204019777',
    actual_pg_name: 'Haveli Boys',
    usp: 'Peak location, newly built with love, pocket friendly',
    highlights: ['Co-ed', 'Budget Friendly', 'Near Ecoworld', 'No Curfew'],
    tier: 'Mid',
  }),

  pg({
    id: 'bella-gc-flats', slug: 'bella-gc-flats',
    name: 'Bella GC Flats Bellandur', gharpayy_name: 'bella gc flats GIRLS',
    area: 'Bellandur', locality: 'Bellandur',
    nearby_landmarks: ['Ecoworld', 'Flipkart'],
    gender_preference: 'any',
    room_types: ['Single Sharing', 'Double Sharing'],
    min_rent: 16000, max_rent: 29000,
    price_range: 'D16K / S29K',
    manager_contact: '9845594559',
    actual_pg_name: 'Arcade Inn',
    usp: 'Newest PG, Prime Location, WFH Enabler, Food Good',
    highlights: ['Flat-Like', 'Near Ecoworld', 'WFH Friendly', 'No Curfew'],
    tier: 'Mid',
  }),

  pg({
    id: 'eco-coed', slug: 'eco-coed',
    name: 'Eco Coed Bellandur', gharpayy_name: 'eco coed',
    area: 'Bellandur', locality: 'Bellandur',
    nearby_landmarks: ['Bellandur'],
    google_maps_url: 'https://maps.app.goo.gl/2VRqASzDKvTc8j7S9',
    gender_preference: 'any',
    room_types: ['Single Sharing', 'Double Sharing', 'Triple Sharing'],
    min_rent: 9000, max_rent: 23000,
    price_range: 'T9K / D13K / S23K',
    manager_contact: '9501231237',
    actual_pg_name: 'Leo',
    usp: 'Peak location, newly built with love, pocket friendly',
    highlights: ['Co-ed', 'Pocket Friendly', 'Near Bellandur', 'No Curfew'],
    tier: 'Mid',
  }),

  pg({
    id: 'qual-girls', slug: 'qual-girls',
    name: 'Qual Girls Bellandur', gharpayy_name: 'qual girls',
    area: 'Bellandur', locality: 'Ecoworld, Bellandur, Flipkart',
    nearby_landmarks: ['Ecoworld', 'Flipkart'],
    gender_preference: 'female',
    room_types: ['Single Sharing', 'Double Sharing', 'Triple Sharing'],
    min_rent: 12000, max_rent: 25000,
    price_range: 'T12K / D15K / S25K',
    actual_pg_name: 'Sapthagiri',
    amenities: [...STD_AMENITIES, 'Library'],
    usp: 'Newly built, GYM, Games. No Curfew',
    highlights: ['Girls Only', 'Library', 'Gym & Games', 'No Curfew'],
    tier: 'Mid',
  }),

  pg({
    id: 'etv-luxe-coed', slug: 'etv-luxe-coed',
    name: 'ETV Luxe Coed Bellandur', gharpayy_name: 'etv luxe coed',
    area: 'Bellandur', locality: 'Ecoworld, Bellandur, Flipkart',
    nearby_landmarks: ['Ecoworld', 'Flipkart'],
    gender_preference: 'any',
    room_types: ['Single Sharing', 'Double Sharing'],
    min_rent: 15000, max_rent: 25000,
    price_range: 'D15K / S25K',
    manager_contact: '9739997392',
    actual_pg_name: 'Echo Coliving',
    amenities: [...STD_AMENITIES, 'Study Area', 'Parking'],
    usp: 'Newest PG, Prime Location, WFH Enabler, Good Food',
    highlights: ['Near Ecoworld', 'WFH Enabler', 'Study Area', 'No Curfew'],
    tier: 'Mid',
  }),

  pg({
    id: 'livio-coed', slug: 'livio-coed',
    name: 'Livio Coed Flatlike Bellandur', gharpayy_name: 'LIVIO COED FLATLIKE',
    area: 'Bellandur', locality: 'Kadubeesanahalli',
    nearby_landmarks: ['New Horizon College'],
    google_maps_url: 'https://maps.app.goo.gl/jaqdRWjiy61txVL39',
    gender_preference: 'any',
    property_type: 'premium',
    room_types: ['Room with Balcony & Common Washroom', 'Room with Attached Washroom', 'Room with Balcony & Attached Washroom'],
    min_rent: 23000, max_rent: 26000,
    price_range: 'Balcony+Common 23K / Attached 24K / Balcony+Attached 26K',
    food_type: 'non-veg',
    actual_pg_name: 'IRA Coliving',
    usp: 'Budget friendly, games, coliving. No Curfew',
    highlights: ['Flat-Like', 'Premium', 'Balcony Rooms', 'No Curfew'],
    tier: 'Classics',
  }),

  pg({
    id: 'zonegl-coed', slug: 'zonegl-coed',
    name: 'Zonegl Coed Bellandur', gharpayy_name: 'ZONEGL',
    area: 'Bellandur', locality: 'Near SJR Bellandur',
    nearby_landmarks: ['Bellandur', 'SJR'],
    gender_preference: 'any',
    property_type: 'premium',
    room_types: ['Single Sharing', 'Double Sharing'],
    min_rent: 13000, max_rent: 25000,
    price_range: 'D13-14K / S24-25K',
    manager_contact: '9110719095',
    actual_pg_name: 'Live Loop',
    usp: 'Near to jogger park',
    highlights: ['Premium', 'Near Park', 'Good Locality', 'No Curfew'],
    tier: 'Mid',
  }),

  pg({
    id: 'elux-coed', slug: 'elux-coed',
    name: 'Elux Coed Bellandur', gharpayy_name: 'ELUX COED',
    area: 'Bellandur', locality: 'Kadubeesanahalli',
    nearby_landmarks: ['Kadubeesanahalli'],
    gender_preference: 'any',
    property_type: 'premium',
    room_types: ['Single Sharing', 'Double Sharing'],
    min_rent: 19000, max_rent: 30000,
    price_range: 'D19K / S30K',
    manager_contact: '7996679993',
    actual_pg_name: 'Infinity Inn Echo',
    noise_level: 'low',
    usp: 'Very luxury property',
    highlights: ['Premium Luxury', 'Low Noise', 'Premium Vibe', 'No Curfew'],
    tier: 'Classics',
    average_rating: 4.9,
  }),

  pg({
    id: 'pavion-coed', slug: 'pavion-coed',
    name: 'Pavion Coed Bellandur/Sarjapur', gharpayy_name: 'PAVION COED',
    area: 'Bellandur', locality: 'Sarjapur, Bellandur',
    nearby_landmarks: ['Bellandur', 'Sarjapur'],
    gender_preference: 'any',
    room_types: ['Single Sharing', 'Double Sharing'],
    min_rent: 14000, max_rent: 25000,
    price_range: 'D13K / S23K',
    actual_pg_name: 'Eden Premium',
    usp: 'Premium budget property',
    highlights: ['Co-ed', 'Budget Premium', 'Good Location', 'No Curfew'],
    tier: 'Mid',
  }),

  pg({
    id: 'sjr-affo-coed', slug: 'sjr-affo-coed',
    name: 'SJR Affo Coed', gharpayy_name: 'SJR AFFO COED',
    area: 'Bellandur', locality: 'Sarjapur, near Wipro SJR Office',
    nearby_landmarks: ['Wipro SJR', 'Sarjapur'],
    google_maps_url: 'https://maps.app.goo.gl/vCsVhjBrjCeQMbHS8',
    gender_preference: 'any',
    room_types: ['Single Sharing', 'Double Sharing'],
    min_rent: 12000, max_rent: 21000,
    price_range: 'D8K / S19K',
    manager_contact: '8951560310',
    actual_pg_name: 'Cabanan Willow Luxe',
    usp: 'Near Wipro SJR office',
    highlights: ['Near Wipro', 'Budget Friendly', 'Coliving', 'No Curfew'],
    tier: 'Mid',
  }),

  // ─── MARATHAHALLI ────────────────────────────────────────────────────────
  pg({
    id: 'mystic-coed', slug: 'mystic-coed',
    name: 'Mystic Coed Marathahalli', gharpayy_name: 'MYSTIC COED',
    area: 'Marathahalli', locality: 'AECS, Marathahalli',
    nearby_landmarks: ['Marathahalli Market'],
    google_maps_url: 'https://maps.app.goo.gl/EydKS2YoehU6uhfm7',
    gender_preference: 'any',
    room_types: ['Single Sharing', 'Double Sharing'],
    min_rent: 13000, max_rent: 24000,
    price_range: 'D13K / S24K',
    manager_contact: '8500931018',
    actual_pg_name: 'Orion Living / Flux Coliving',
    usp: 'Budget friendly, games, coliving',
    highlights: ['Co-ed', 'Budget Friendly', 'Games', 'No Curfew'],
    tier: 'Mid',
  }),

  pg({
    id: 'zion-luxe-coed', slug: 'zion-luxe-coed',
    name: 'Zion Luxe Coed Marathahalli', gharpayy_name: 'ZION LUXE COED',
    area: 'Marathahalli', locality: 'AECS, Marathahalli',
    nearby_landmarks: ['Marathahalli Market'],
    google_maps_url: 'https://maps.app.goo.gl/X9FTMTJSxecwgWsG6',
    gender_preference: 'any',
    room_types: ['Single Sharing', 'Double Sharing', 'Double Sharing Suite'],
    min_rent: 13000, max_rent: 27000,
    price_range: 'D13K / Suite16K / S27K',
    manager_contact: '7993429799',
    actual_pg_name: 'Orion Coliving',
    usp: 'Budget friendly, games, coliving',
    highlights: ['Co-ed', 'Suite Rooms', 'Games', 'No Curfew'],
    tier: 'Mid',
  }),

  pg({
    id: 'gg-vistra', slug: 'gg-vistra',
    name: 'GG Vistra Marathahalli', gharpayy_name: 'Gg Vistra',
    area: 'Marathahalli', locality: 'AECS, Marathahalli',
    nearby_landmarks: ['Marathahalli Market'],
    gender_preference: 'any',
    room_types: ['Single Sharing', 'Double Sharing', 'Triple Sharing'],
    min_rent: 11000, max_rent: 23000,
    price_range: 'T11K / D13K / S20K',
    owner_contact: '9052818503',
    actual_pg_name: 'At Homes',
    usp: 'Budget friendly, games, coliving',
    highlights: ['Co-ed', 'Budget Friendly', 'Coliving', 'No Curfew'],
    tier: 'Mid',
  }),

  pg({
    id: 'kmahalli-coed', slug: 'kmahalli-coed',
    name: 'KMahalli Coed Marathahalli', gharpayy_name: 'Kmahalli coed',
    area: 'Marathahalli', locality: 'AECS, Marathahalli',
    nearby_landmarks: ['Marathahalli Market'],
    google_maps_url: 'https://maps.app.goo.gl/WATeMBV11LFhfcxU6',
    gender_preference: 'any',
    room_types: ['Single Sharing', 'Double Sharing', 'Triple Sharing'],
    min_rent: 10000, max_rent: 23000,
    price_range: 'T10K / D13K / S23K',
    owner_contact: '9353999534',
    actual_pg_name: 'Avalon Luxe',
    usp: 'Budget friendly, games, coliving',
    highlights: ['Co-ed', 'Budget Friendly', 'Coliving', 'No Curfew'],
    tier: 'Mid',
  }),

  pg({
    id: 'solaria-coed', slug: 'solaria-coed',
    name: 'Solaria Coed Marathahalli', gharpayy_name: 'Solaria Coed',
    area: 'Marathahalli', locality: 'Marathahalli',
    nearby_landmarks: ['Marathahalli Market', 'ITPL', 'ORR'],
    gender_preference: 'any',
    room_types: ['Single Sharing', 'Double Sharing', 'Triple Sharing'],
    min_rent: 10000, max_rent: 23000,
    price_range: 'T10K / D13K / S23K',
    owner_contact: '9606798347',
    actual_pg_name: 'GG Klear x Medha Sri Classic',
    usp: 'Budget friendly, games, coliving',
    highlights: ['Co-ed', 'Budget Friendly', 'Games', 'No Curfew'],
    tier: 'Mid',
  }),

  pg({
    id: 'klear-coed', slug: 'klear-coed',
    name: 'Klear Coed Marathahalli', gharpayy_name: 'Klear coed',
    area: 'Marathahalli', locality: 'AECS, Marathahalli',
    nearby_landmarks: ['Marathahalli Market'],
    google_maps_url: 'https://maps.app.goo.gl/WATeMBV11LFhfcxU6',
    gender_preference: 'any',
    room_types: ['Single Sharing', 'Double Sharing', 'Triple Sharing'],
    min_rent: 10000, max_rent: 23000,
    price_range: 'T10K / D13K / S23K',
    actual_pg_name: 'Klear x Medha Sri Classic',
    usp: 'Budget friendly, games, coliving',
    highlights: ['Co-ed', 'Budget Friendly', 'Coliving', 'No Curfew'],
    tier: 'Mid',
  }),

  pg({
    id: 'klm-coed', slug: 'klm-coed',
    name: 'KLM Coed Marathahalli', gharpayy_name: 'KLM COED',
    area: 'Marathahalli', locality: 'Marathahalli',
    nearby_landmarks: ['Marathahalli Market'],
    gender_preference: 'any',
    room_types: ['Single Sharing', 'Double Sharing'],
    min_rent: 11000, max_rent: 22000,
    price_range: 'D11K / S20K',
    owner_contact: '9110533155',
    actual_pg_name: 'Chap and Dona',
    usp: 'Good location',
    highlights: ['Co-ed', 'Good Location', 'Budget Friendly', 'No Curfew'],
    tier: 'Mid',
  }),

  pg({
    id: 'maq-coed', slug: 'maq-coed',
    name: 'MAQ Coed Marathahalli', gharpayy_name: 'MAQ COED',
    area: 'Marathahalli', locality: 'Marathahalli',
    nearby_landmarks: ['Marathahalli Market'],
    gender_preference: 'any',
    room_types: ['Single Sharing', 'Double Sharing'],
    min_rent: 13000, max_rent: 25000,
    price_range: 'D13K / S24K',
    manager_contact: '8309733994',
    actual_pg_name: 'Vow Living',
    usp: 'Good locality',
    highlights: ['Co-ed', 'Good Locality', 'Budget Friendly', 'No Curfew'],
    tier: 'Mid',
  }),

  pg({
    id: 'aura-coed', slug: 'aura-coed',
    name: 'Aura Coed Marathahalli', gharpayy_name: 'AURA COED',
    area: 'Marathahalli', locality: 'AECS, Marathahalli',
    nearby_landmarks: ['Marathahalli Market', 'AECS'],
    gender_preference: 'any',
    room_types: ['Single Sharing', 'Double Sharing'],
    min_rent: 15000, max_rent: 31000,
    price_range: 'D-Deluxe15K / D-Premium17K / S31K',
    actual_pg_name: 'Zen Co-Living',
    usp: 'Spacious premium property',
    highlights: ['Co-ed', 'Premium', 'Spacious Rooms', 'No Curfew'],
    tier: 'Classics',
  }),

  pg({
    id: 'mune-coed', slug: 'mune-coed',
    name: 'Mune Coed Marathahalli', gharpayy_name: 'MUNE COED',
    area: 'Marathahalli', locality: 'Marathahalli, Sarjapur',
    nearby_landmarks: ['Marathahalli Market', 'Marathahalli Bridge'],
    google_maps_url: 'https://maps.app.goo.gl/oS1iuL4KF4Lt4YQcA',
    gender_preference: 'any',
    property_type: 'budget',
    room_types: ['Single Sharing', 'Double Sharing'],
    min_rent: 11000, max_rent: 20000,
    price_range: 'D11K / S20K',
    manager_contact: '9986866022',
    actual_pg_name: 'Kumar Lavander House / Sankalpa Co-live & Guest',
    usp: 'Budget friendly',
    highlights: ['Co-ed', 'Budget', 'Coliving', 'No Curfew'],
    tier: 'Budget',
  }),

  pg({
    id: 'gg-nuovo-boys', slug: 'gg-nuovo-boys',
    name: 'GG Nuovo Boys HSR Layout', gharpayy_name: 'Gg Nuovo BOYS',
    area: 'HSR Layout', locality: 'HSR, Silk Board',
    nearby_landmarks: ['HSR Layout', 'Silk Board'],
    gender_preference: 'male',
    room_types: ['Single Sharing', 'Double Sharing', 'Triple Sharing'],
    min_rent: 8000, max_rent: 21000,
    price_range: 'T8K / D12K / S21K',
    manager_contact: '9032266177',
    actual_pg_name: 'Gayathri PG',
    usp: 'Extremely budget friendly, mini gym & games',
    highlights: ['Boys Only', 'Budget Friendly', 'Gym', 'No Curfew'],
    tier: 'Mid',
  }),

  // ─── MAHADEVAPURA ────────────────────────────────────────────────────────
  pg({
    id: 'zeal-coed', slug: 'zeal-coed',
    name: 'Zeal Coed Mahadevapura', gharpayy_name: 'Zeal Coed',
    area: 'Mahadevapura', locality: 'Bagmane, CV Raman',
    nearby_landmarks: ['EY', 'Coral Building', 'Bagmane World Technology Center'],
    google_maps_url: 'https://maps.app.goo.gl/9Qiz9B2S7VzVkagd8',
    gender_preference: 'any',
    room_types: ['Single Sharing', 'Double Sharing'],
    min_rent: 12000, max_rent: 22000,
    price_range: 'D12K / S22K',
    manager_contact: '7829930666',
    actual_pg_name: 'Blis Comfort',
    usp: 'Extremely budget friendly, mini gym & games, coliving',
    highlights: ['Co-ed', 'Near Bagmane', 'Budget Friendly', 'No Curfew'],
    tier: 'Mid',
  }),

  pg({
    id: 'prive-coed', slug: 'prive-coed',
    name: 'Prive Coed Mahadevapura', gharpayy_name: 'PRIVE COED',
    area: 'Mahadevapura', locality: 'Bagmane, CV Raman',
    nearby_landmarks: ['Bagmane Tech Park', 'EY', 'Bagmane WTC'],
    google_maps_url: 'https://maps.app.goo.gl/8tywjuxAm62CEUrk9',
    gender_preference: 'any',
    room_types: ['Single Sharing', 'Double Sharing'],
    min_rent: 15000, max_rent: 25000,
    price_range: 'D15K / S25K',
    actual_pg_name: 'Primestay',
    usp: 'Extremely budget friendly, mini gym & games, coliving',
    highlights: ['Co-ed', 'Near Bagmane', 'Gym & Games', 'No Curfew'],
    tier: 'Mid',
  }),

  pg({
    id: 'mivon-coed', slug: 'mivon-coed',
    name: 'Mivon Coed Mahadevapura', gharpayy_name: 'MIVON COED',
    area: 'Mahadevapura', locality: 'Bagmane, CV Raman',
    nearby_landmarks: ['EY', 'Coral Building', 'Bagmane WTC'],
    google_maps_url: 'https://maps.app.goo.gl/A2gTtGAhC4GfLByK9',
    gender_preference: 'any',
    room_types: ['Single Sharing', 'Double Sharing', 'Double Sharing Suite'],
    min_rent: 15000, max_rent: 28000,
    price_range: 'D15K / Suite16K / S28K',
    manager_contact: '7729858699',
    actual_pg_name: 'Urban Coliving',
    usp: 'Extremely budget friendly, mini gym & games, coliving',
    highlights: ['Co-ed', 'Suite Rooms', 'Near Bagmane', 'No Curfew'],
    tier: 'Mid',
  }),

  pg({
    id: 'bigbrook-coed', slug: 'bigbrook-coed',
    name: 'Bigbrook Coed Mahadevapura', gharpayy_name: 'BIGBROOK',
    area: 'Mahadevapura', locality: 'Brookfield, Mahadevapura',
    nearby_landmarks: ['EY', 'Coral Building', 'Bagmane WTC'],
    google_maps_url: 'https://maps.app.goo.gl/1JSY7tnYhzS6TxtU9',
    gender_preference: 'any',
    room_types: ['Single Sharing', 'Double Sharing'],
    min_rent: 17000, max_rent: 30000,
    price_range: 'D17K / S30K',
    actual_pg_name: 'Apex Coliving',
    amenities: [...STD_AMENITIES, 'Parking'],
    usp: 'Budget friendly, games, coliving',
    highlights: ['Co-ed', 'Near Bagmane', 'Games', 'No Curfew'],
    tier: 'Mid',
  }),

  pg({
    id: 'zeest-coed', slug: 'zeest-coed',
    name: 'Zeest Coed Mahadevapura', gharpayy_name: 'Zeest COED',
    area: 'Mahadevapura', locality: 'Brookfield, Mahadevapura',
    nearby_landmarks: ['EY', 'Coral Building', 'Bagmane WTC'],
    google_maps_url: 'https://maps.app.goo.gl/xpp8Ekvknp7NxdUAA',
    gender_preference: 'any',
    room_types: ['Single Sharing', 'Double Sharing'],
    min_rent: 14000, max_rent: 24000,
    price_range: 'D14K / S24K',
    manager_contact: '8985878106',
    actual_pg_name: 'Wix Coliving Mahadevapura',
    usp: 'Budget friendly, games, coliving',
    highlights: ['Co-ed', 'Near Bagmane', 'Games', 'No Curfew'],
    tier: 'Mid',
  }),

  pg({
    id: 'cool-coed-balc', slug: 'cool-coed-balc',
    name: 'Cool Coed Balcony Mahadevapura', gharpayy_name: 'Cool coed balc',
    area: 'Mahadevapura', locality: 'Brookfield, Mahadevapura',
    nearby_landmarks: ['EY', 'Coral Building', 'Bagmane WTC'],
    gender_preference: 'any',
    room_types: ['Single Sharing', 'Double Sharing'],
    min_rent: 16000, max_rent: 26000,
    price_range: 'D16K / S26K',
    manager_contact: '8688790159',
    owner_contact: '8555810106',
    actual_pg_name: 'Qix Coliving',
    usp: 'Newest PG, Prime Location, WFH Enabler, Food Good',
    highlights: ['Co-ed', 'Balcony Rooms', 'Near Bagmane', 'No Curfew'],
    tier: 'Mid',
  }),

  pg({
    id: 'itp-coed', slug: 'itp-coed',
    name: 'ITP Coed Mahadevapura', gharpayy_name: 'ITP coed',
    area: 'Mahadevapura', locality: 'Brookfield, Whitefield',
    nearby_landmarks: ['EY', 'Coral Building', 'Bagmane WTC'],
    gender_preference: 'any',
    room_types: ['Single Sharing', 'Double Sharing', 'Triple Sharing'],
    min_rent: 10000, max_rent: 23000,
    price_range: 'T10K / D13K / S22K',
    manager_contact: '9164515777',
    actual_pg_name: 'AA Premium Coliving',
    usp: 'Newest PG, Prime Location, WFH Enabler, Food Good',
    highlights: ['Co-ed', 'Prime Location', 'WFH Enabler', 'No Curfew'],
    tier: 'Mid',
  }),

  pg({
    id: 'itp-one-coed', slug: 'itp-one-coed',
    name: 'ITP One Coed Mahadevapura', gharpayy_name: 'itp one coed',
    area: 'Mahadevapura', locality: 'Brookfield, Whitefield',
    nearby_landmarks: ['EY', 'Coral Building', 'Bagmane WTC'],
    gender_preference: 'any',
    room_types: ['Single Sharing', 'Double Sharing', 'Triple Sharing'],
    min_rent: 10000, max_rent: 23000,
    price_range: 'T10K / D13K / S22K',
    manager_contact: '9164515777',
    actual_pg_name: 'AA Premium Coliving Block B',
    usp: 'Newest PG, Prime Location, WFH Enabler, Food Good',
    highlights: ['Co-ed', 'WFH Enabler', 'Prime Location', 'No Curfew'],
    tier: 'Mid',
  }),

  pg({
    id: 'thub-coed', slug: 'thub-coed',
    name: 'Thub Coed Mahadevapura', gharpayy_name: 'thub coed',
    area: 'Mahadevapura', locality: 'Brookfield, ITPL, Whitefield',
    nearby_landmarks: ['EY', 'Coral Building', 'Bagmane WTC'],
    gender_preference: 'any',
    room_types: ['Single Sharing', 'Double Sharing'],
    min_rent: 13000, max_rent: 23000,
    price_range: 'D13K / S23K',
    manager_contact: '9164203777',
    actual_pg_name: 'Urban Coliving',
    usp: 'Budget friendly, games, coliving',
    highlights: ['Co-ed', 'Budget Friendly', 'Near Bagmane', 'No Curfew'],
    tier: 'Mid',
  }),

  pg({
    id: 'phix-bgm', slug: 'phix-bgm',
    name: 'Phix BGM Coed Mahadevapura', gharpayy_name: 'PHIX BGM',
    area: 'Mahadevapura', locality: 'Mahadevapura, Bagmane',
    nearby_landmarks: ['EY', 'Coral Building', 'Bagmane WTC'],
    google_maps_url: 'https://maps.app.goo.gl/1etTC7JAqtfc6KKp6',
    gender_preference: 'any',
    room_types: ['Single Sharing', 'Double Sharing'],
    min_rent: 12500, max_rent: 22000,
    price_range: 'D12.5K / S22K',
    manager_contact: '7730811511',
    owner_contact: '9663194940',
    actual_pg_name: 'SR Comfort',
    food_type: 'both',
    usp: 'New property, very close to Bagmane Tech Park, good food, premium stay',
    highlights: ['Near Bagmane', 'Non-Veg Food', 'Premium Stay', 'No Curfew'],
    tier: 'Mid',
  }),

  pg({
    id: 'balc-phix-bgm', slug: 'balc-phix-bgm',
    name: 'Balc Phix BGM Coed Mahadevapura', gharpayy_name: 'BALC PHIX BGM COED',
    area: 'Mahadevapura', locality: 'Bagmane, CV Raman',
    nearby_landmarks: ['EY', 'Coral Building', 'Bagmane WTC'],
    gender_preference: 'any',
    room_types: ['Single Sharing', 'Double Sharing'],
    min_rent: 13000, max_rent: 24000,
    price_range: 'D13K / S24K',
    manager_contact: '9959829782',
    actual_pg_name: 'KS Bloom',
    food_type: 'both',
    usp: 'New property, very close to Bagmane Tech Park, good food, premium stay',
    highlights: ['Balcony Rooms', 'Near Bagmane', 'Non-Veg Food', 'No Curfew'],
    tier: 'Mid',
  }),

  pg({
    id: 'bgm-max-coed', slug: 'bgm-max-coed',
    name: 'BGM Max Coed Mahadevapura', gharpayy_name: 'bgm max coed',
    area: 'Mahadevapura', locality: 'Bagmane, CV Raman',
    nearby_landmarks: ['EY', 'Coral Building', 'Bagmane WTC'],
    google_maps_url: 'https://maps.app.goo.gl/QuLYHW5y9i1yt1qQA',
    gender_preference: 'any',
    room_types: ['Single Sharing', 'Double Sharing'],
    min_rent: 13000, max_rent: 23000,
    price_range: 'D13K / S21K',
    manager_contact: '7013603027',
    owner_contact: '7204019777',
    actual_pg_name: 'Mr & Mrs Mahadev',
    usp: 'Extremely budget friendly, mini gym & games, coliving',
    highlights: ['Co-ed', 'Budget Friendly', 'Near Bagmane', 'No Curfew'],
    tier: 'Mid',
  }),

  pg({
    id: 'esteem-coed', slug: 'esteem-coed',
    name: 'Esteem Coed Mahadevapura', gharpayy_name: 'ESTEEM COED',
    area: 'Mahadevapura', locality: 'Bagmane, CV Raman',
    nearby_landmarks: ['EY', 'Coral Building', 'Bagmane WTC'],
    gender_preference: 'any',
    room_types: ['Single Sharing', 'Double Sharing'],
    min_rent: 14000, max_rent: 25000,
    price_range: 'D14K / S25K',
    manager_contact: '9912969023',
    owner_contact: '7204019777',
    actual_pg_name: 'Signature Colive',
    usp: 'New PG, all amenities, premium property',
    highlights: ['New PG', 'Premium', 'Near Bagmane', 'No Curfew'],
    tier: 'Mid',
  }),

  pg({
    id: 'finn-affo-coed', slug: 'finn-affo-coed',
    name: 'Finn Affo Coed Mahadevapura', gharpayy_name: 'FINN AFFO COED',
    area: 'Mahadevapura', locality: 'Mahadevapura, Marathahalli',
    nearby_landmarks: ['Marathahalli Market', 'AECS', 'Bagmane WTC'],
    gender_preference: 'any',
    property_type: 'budget',
    room_types: ['Single Sharing', 'Double Sharing', 'Triple Sharing'],
    min_rent: 9500, max_rent: 25000,
    price_range: 'T9.5K / D14K / S23-24K',
    actual_pg_name: 'SV Classic Coliving',
    usp: 'Budget friendly',
    highlights: ['Co-ed', 'Budget', 'Coliving', 'No Curfew'],
    tier: 'Budget',
  }),

  pg({
    id: 'zeeta-coed', slug: 'zeeta-coed',
    name: 'Zeeta Coed Whitefield', gharpayy_name: 'Zeeta coed',
    area: 'Whitefield', locality: 'Whitefield, ITPL',
    nearby_landmarks: ['ITPL', 'Whitefield', 'Hopefarm'],
    gender_preference: 'any',
    room_types: ['Single Sharing', 'Double Sharing'],
    min_rent: 10000, max_rent: 21000,
    price_range: 'D10K / S19K',
    actual_pg_name: 'Elite4',
    usp: 'Budget friendly',
    highlights: ['Co-ed', 'Budget Friendly', 'Near ITPL', 'No Curfew'],
    tier: 'Mid',
  }),

  // ─── NAGAWARA / MANYATA ──────────────────────────────────────────────────
  pg({
    id: 'cia-coed', slug: 'cia-coed',
    name: 'CIA Coed Nagawara/Manyata', gharpayy_name: 'CIA COED',
    area: 'Nagawara', locality: 'Manyata',
    nearby_landmarks: ['Manyata Tech Park'],
    google_maps_url: 'https://maps.app.goo.gl/rgAoSF42L1NFdeGp7',
    gender_preference: 'any',
    room_types: ['Single Sharing', 'Double Sharing'],
    min_rent: 13000, max_rent: 22000,
    price_range: 'D13K / S22K',
    manager_contact: '7022568295',
    owner_contact: '9916669290',
    actual_pg_name: 'Gopu x Gharpayy / MG Gopu Homestays G4',
    meals_included: 2,
    safety_features: [...STD_SAFETY, 'Biometric Access'],
    usp: 'Good PG, Prime Location, WFH Enabler, Food Good. No curfew',
    highlights: ['Co-ed', 'Near Manyata', 'WFH Enabler', 'No Curfew'],
    tier: 'Mid',
  }),

  pg({
    id: 'magnus-coed', slug: 'magnus-coed',
    name: 'Magnus Coed Nagawara/Manyata', gharpayy_name: 'Magnus COED',
    area: 'Nagawara', locality: 'Manyata',
    nearby_landmarks: ['Manyata Tech Park'],
    google_maps_url: 'https://maps.app.goo.gl/wVcQBggkCpdj2cMB7',
    gender_preference: 'any',
    room_types: ['Single Sharing', 'Double Sharing', 'Triple Sharing'],
    min_rent: 9000, max_rent: 17000,
    price_range: 'T9K / D12K / S15K',
    owner_contact: '7997477685',
    actual_pg_name: 'Surya Coliving PG',
    usp: 'New property, no curfew',
    highlights: ['Co-ed', 'Budget Friendly', 'New Property', 'No Curfew'],
    tier: 'Mid',
  }),

  pg({
    id: 'mtplus-coed', slug: 'mtplus-coed',
    name: 'MT Plus Coed Nagawara/Manyata', gharpayy_name: 'MTPLUS COED',
    area: 'Nagawara', locality: 'Manyata, Hebbal',
    nearby_landmarks: ['Hebbal', 'Manyata Tech Park'],
    gender_preference: 'any',
    room_types: ['Single Sharing', 'Double Sharing'],
    min_rent: 13000, max_rent: 22000,
    price_range: 'D13K / S22K',
    owner_contact: '9620785999',
    actual_pg_name: 'Surya Royal Homes',
    usp: 'Extremely budget friendly, mini gym & games, coliving',
    highlights: ['Co-ed', 'Near Manyata', 'Budget Friendly', 'No Curfew'],
    tier: 'Mid',
  }),

  pg({
    id: 'mtek-coed', slug: 'mtek-coed',
    name: 'MTek Coed Nagawara/Manyata', gharpayy_name: 'MTEK coed',
    area: 'Nagawara', locality: 'Manyata',
    nearby_landmarks: ['Manyata Tech Park'],
    gender_preference: 'any',
    room_types: ['Single Sharing', 'Double Sharing'],
    min_rent: 11000, max_rent: 20000,
    price_range: 'D11K / S20K',
    owner_contact: '9620785999',
    actual_pg_name: 'Surya Royal Homes',
    food_type: 'both',
    usp: 'Newly built, Games. No Curfew',
    highlights: ['Co-ed', 'New Property', 'Near Manyata', 'No Curfew'],
    tier: 'Mid',
  }),

  pg({
    id: 'wista-girls-c', slug: 'wista-girls-c',
    name: 'Wista Girls C Nagawara/Manyata', gharpayy_name: 'WISTA GIRLS C',
    area: 'Nagawara', locality: 'Manyata',
    nearby_landmarks: ['Manyata Tech Park'],
    google_maps_url: 'https://maps.app.goo.gl/hMYCpCqMosvzbnrQ9',
    gender_preference: 'female',
    room_types: ['Single Sharing', 'Double Sharing'],
    min_rent: 12000, max_rent: 21000,
    price_range: 'D10-11K / S18-19K',
    manager_contact: '9008801504',
    actual_pg_name: 'Surya Royal Homes / Blossom Girls',
    usp: 'New property, no curfew',
    highlights: ['Girls Only', 'New Property', 'Near Manyata', 'No Curfew'],
    tier: 'Mid',
  }),

  // ─── ELECTRONIC CITY ─────────────────────────────────────────────────────
  pg({
    id: 'flex-coed', slug: 'flex-coed',
    name: 'Flex Coed Electronic City', gharpayy_name: 'FLEX COED',
    area: 'Electronic City', locality: 'Shanthipura, Electronic City',
    nearby_landmarks: ['Semicon Park', 'Tech37'],
    google_maps_url: 'https://maps.app.goo.gl/oQYZPJRAYMoQwhp29',
    gender_preference: 'any',
    room_types: ['Single Sharing', 'Double Sharing', 'Triple Sharing'],
    min_rent: 9000, max_rent: 17000,
    price_range: 'T8K / D11K / S17K',
    owner_contact: '9515775563',
    actual_pg_name: 'P2 Liv In / eCity Phase 2',
    accessibility: ['Metro', 'Bus'],
    safety_features: [...STD_SAFETY, 'Biometric Access'],
    usp: 'Great property, games, very nearby to offices',
    highlights: ['Co-ed', 'Near Semicon Park', 'Budget Friendly', 'No Curfew'],
    tier: 'Mid',
  }),

  pg({
    id: 'pop-coed', slug: 'pop-coed',
    name: 'Pop Coed Electronic City', gharpayy_name: 'POP COED',
    area: 'Electronic City', locality: 'Electronic City',
    nearby_landmarks: ['Tech 37', 'Infosys'],
    gender_preference: 'any',
    room_types: ['Single Sharing', 'Double Sharing'],
    min_rent: 10000, max_rent: 16000,
    price_range: 'D10K / S16K',
    owner_contact: '9989285854',
    actual_pg_name: 'Leo PG',
    usp: 'Great property, games, very nearby to offices',
    highlights: ['Co-ed', 'Near Infosys', 'Budget Friendly', 'No Curfew'],
    tier: 'Mid',
  }),

  pg({
    id: 'quo-coed', slug: 'quo-coed',
    name: 'Quo Coed Electronic City', gharpayy_name: 'Quo coed',
    area: 'Electronic City', locality: 'Electronic City',
    nearby_landmarks: ['Tech 37', 'Infosys'],
    gender_preference: 'any',
    room_types: ['Single Sharing', 'Double Sharing'],
    min_rent: 10000, max_rent: 16000,
    price_range: 'D10K / S16K',
    owner_contact: '9989285854',
    actual_pg_name: 'Grand Inn',
    accessibility: ['Metro', 'Bus'],
    usp: 'Great property, games, very nearby to offices',
    highlights: ['Co-ed', 'Near Tech 37', 'Metro Access', 'No Curfew'],
    tier: 'Mid',
  }),

  // ─── WHITEFIELD ──────────────────────────────────────────────────────────
  pg({
    id: 'metrofield-coed', slug: 'metrofield-coed',
    name: 'Metrofield Coed Whitefield', gharpayy_name: 'METROFIELD COED',
    area: 'Whitefield', locality: 'Hopefarm, ITPL, Whitefield',
    nearby_landmarks: ['ITPL', 'Whitefield'],
    google_maps_url: 'https://maps.app.goo.gl/mg2SiKg9ZeoND79v6',
    gender_preference: 'any',
    room_types: ['Single Sharing', 'Double Sharing'],
    min_rent: 15000, max_rent: 24000,
    price_range: 'D15K / S24K',
    manager_contact: '9008122779',
    actual_pg_name: 'Hektor',
    accessibility: ['Metro', 'Bus'],
    usp: 'Flat type setup with sofa, fridge, TV. 2W parking. Daily cleaning',
    highlights: ['Metro Connectivity', 'Flat-Like Setup', 'Near ITPL', 'No Curfew'],
    tier: 'Mid',
  }),

  pg({
    id: 'whit-coed', slug: 'whit-coed',
    name: 'Whit Coed Whitefield', gharpayy_name: 'WHIT COED',
    area: 'Whitefield', locality: 'Hopefarm, ITPL, Whitefield',
    nearby_landmarks: ['ITPL', 'Whitefield'],
    google_maps_url: 'https://maps.app.goo.gl/gWyt5JCjXRZed4WY6',
    gender_preference: 'any',
    room_types: ['Single Sharing', 'Double Sharing'],
    min_rent: 9000, max_rent: 17000,
    price_range: 'D9K / S16K',
    manager_contact: '8639653441',
    actual_pg_name: 'OKA Colive',
    accessibility: ['Metro', 'Bus'],
    usp: 'Balcony room, budget stay, food included',
    highlights: ['Balcony Rooms', 'Budget Friendly', 'Near ITPL', 'No Curfew'],
    tier: 'Mid',
  }),

  pg({
    id: 'astor-coed', slug: 'astor-coed',
    name: 'Astor Coed Whitefield', gharpayy_name: 'ASTOR COED',
    area: 'Whitefield', locality: 'Hopefarm, ITPL, Whitefield',
    nearby_landmarks: ['ITPL', 'Whitefield'],
    google_maps_url: 'https://maps.app.goo.gl/N5Ry9TEyMeFHptTJ7',
    gender_preference: 'any',
    room_types: ['Single Sharing', 'Double Sharing'],
    min_rent: 14000, max_rent: 24000,
    price_range: 'D12K / S22K',
    manager_contact: '9880077036',
    actual_pg_name: 'Madhura Co-Living PG',
    accessibility: ['Metro', 'Bus'],
    usp: 'Balcony rooms',
    highlights: ['Balcony Rooms', 'Near ITPL', 'Good Location', 'No Curfew'],
    tier: 'Mid',
  }),

  pg({
    id: 'bliss-whitefield', slug: 'bliss-whitefield',
    name: 'Bliss Coed Whitefield/Brookfield', gharpayy_name: 'Bliss Whitefield',
    area: 'Whitefield', locality: 'Brookfield, AECS, Hopefarm',
    nearby_landmarks: ['ITPL', 'Whitefield', 'Brookfield'],
    google_maps_url: 'https://maps.app.goo.gl/Q45VDHrjtKDtfkR87',
    gender_preference: 'any',
    room_types: ['Single Sharing', 'Double Sharing'],
    min_rent: 13000, max_rent: 23000,
    price_range: 'D11K / S20-21K',
    manager_contact: '9964718777',
    owner_contact: '7204019777',
    actual_pg_name: 'Haveli Coliving',
    accessibility: ['Metro', 'Bus'],
    usp: 'Newly built, Games. No Curfew',
    highlights: ['Co-ed', 'Near ITPL', 'Balcony', 'No Curfew'],
    tier: 'Mid',
  }),

  pg({
    id: 'snowy-luxe', slug: 'snowy-luxe',
    name: 'Snowy Luxe Whitefield', gharpayy_name: 'Snowy Luxe',
    area: 'Whitefield', locality: 'Brookfield, AECS, Hopefarm',
    nearby_landmarks: ['ITPL', 'Whitefield'],
    google_maps_url: 'https://maps.app.goo.gl/gWyt5JCjXRZed4WY6',
    gender_preference: 'any',
    noise_level: 'low',
    room_types: ['Single Sharing', 'Double Sharing'],
    min_rent: 13000, max_rent: 23000,
    price_range: 'D13K / S23K',
    actual_pg_name: 'Pro 4 Posh',
    amenities: [...STD_AMENITIES, 'Study Area'],
    usp: 'Extremely budget friendly, mini gym & games, coliving',
    highlights: ['Co-ed', 'Budget Friendly', 'Low Noise', 'No Curfew'],
    tier: 'Mid',
  }),

  pg({
    id: 'ark-coed', slug: 'ark-coed',
    name: 'ARK Coed Whitefield', gharpayy_name: 'ARK COED',
    area: 'Whitefield', locality: 'White Rose Layout, Whitefield',
    nearby_landmarks: ['Whitefield', 'ITPL'],
    gender_preference: 'any',
    room_types: ['Single Sharing', 'Double Sharing'],
    min_rent: 13000, max_rent: 23000,
    price_range: 'D12K / S22K',
    manager_contact: '8186933794',
    actual_pg_name: 'Arcadian Livinn',
    accessibility: ['Metro', 'Bus', 'Bike'],
    usp: 'Affordable property',
    highlights: ['Co-ed', 'Budget Friendly', 'Near Whitefield', 'No Curfew'],
    tier: 'Mid',
  }),

  pg({
    id: 'itp-luxe-coed', slug: 'itp-luxe-coed',
    name: 'ITP Luxe Coed Whitefield', gharpayy_name: 'ITP LUXE COED',
    area: 'Whitefield', locality: 'Near ITPL',
    nearby_landmarks: ['ITPL', 'Whitefield'],
    gender_preference: 'any',
    property_type: 'premium',
    room_types: ['Single Sharing', 'Double Sharing'],
    min_rent: 15000, max_rent: 31000,
    price_range: 'D-Deluxe15K / D-Premium16.5K / S-Deluxe28K / S-Premium31K',
    manager_contact: '9008014550',
    actual_pg_name: 'FF21Z Hub',
    accessibility: ['Metro', 'Bus', 'Bike'],
    usp: 'Very premium and furnished',
    highlights: ['Premium Luxury', 'Near ITPL', 'Fully Furnished', 'No Curfew'],
    tier: 'Classics',
  }),

  pg({
    id: 'swizz-luxe-coed', slug: 'swizz-luxe-coed',
    name: 'Swizz Luxe Coed Brookfield', gharpayy_name: 'SWIZZ LUXE COED',
    area: 'Whitefield', locality: 'Brookfield',
    nearby_landmarks: ['Marathahalli Market', 'AECS'],
    gender_preference: 'any',
    property_type: 'premium',
    room_types: ['Single Sharing', 'Double Sharing', 'Triple Sharing'],
    min_rent: 13000, max_rent: 30000,
    price_range: 'T-Deluxe13K / T-Premium13.5K / D-Deluxe18K / D-Premium19K / S30K',
    manager_contact: '7996155599',
    actual_pg_name: 'Astraa Grande Coliving',
    usp: 'Wakefit 8 inch orthopaedic mattress',
    highlights: ['Premium', 'PS4 Gaming', 'Rooftop', 'No Curfew'],
    tier: 'Classics',
  }),

  pg({
    id: 'brookluxe-coed', slug: 'brookluxe-coed',
    name: 'Brookluxe Coed Brookfield', gharpayy_name: 'BROOKLUXE COED',
    area: 'Whitefield', locality: 'AECS, Brookfield',
    nearby_landmarks: ['Marathahalli Market'],
    gender_preference: 'any',
    property_type: 'premium',
    room_types: ['Single Sharing', 'Double Sharing'],
    min_rent: 15000, max_rent: 27000,
    price_range: 'D15K / S25K',
    actual_pg_name: 'AA Sparrow',
    amenities: [...STD_AMENITIES, 'Study Area', 'Parking', 'Biometric'],
    usp: 'Budget friendly, mini games, coliving',
    highlights: ['Premium', 'Brookfield', 'Coliving', 'No Curfew'],
    tier: 'Classics',
  }),

  pg({
    id: 'zeluxe-coed', slug: 'zeluxe-coed',
    name: 'Zeluxe Coed Brookfield', gharpayy_name: 'ZELUXE COED',
    area: 'Whitefield', locality: 'AECS, Brookfield',
    nearby_landmarks: ['Marathahalli Market'],
    gender_preference: 'any',
    property_type: 'premium',
    room_types: ['Single Sharing', 'Double Sharing'],
    min_rent: 18000, max_rent: 35000,
    price_range: 'D18K / S35K',
    actual_pg_name: 'VSR Dwell',
    usp: 'Premium furnished',
    highlights: ['Premium Luxury', 'Brookfield', 'Fully Furnished', 'No Curfew'],
    tier: 'Classics',
  }),

  pg({
    id: 'sf-valley', slug: 'sf-valley',
    name: 'SF Valley Coed Whitefield', gharpayy_name: 'SF VALLEY',
    area: 'Whitefield', locality: 'Hopefarm, ITPL, Whitefield',
    nearby_landmarks: ['ITPL', 'Whitefield'],
    gender_preference: 'any',
    room_types: ['Single Sharing', 'Double Sharing'],
    min_rent: 15000, max_rent: 27000,
    price_range: 'D15K / S27K',
    actual_pg_name: 'Yello',
    meals_included: 0,
    food_type: 'self-cook',
    accessibility: ['Metro', 'Bus'],
    usp: 'Great property, newly, GYM, GAMES. No curfew',
    highlights: ['Co-ed', 'Self-Cook Option', 'Near ITPL', 'No Curfew'],
    tier: 'Mid',
  }),

  pg({
    id: 'mexa-coed', slug: 'mexa-coed',
    name: 'Mexa Coed Whitefield', gharpayy_name: 'MEXA COED',
    area: 'Whitefield', locality: 'Naruhalli, Whitefield',
    nearby_landmarks: ['Whitefield Metro', 'Naruhalli'],
    gender_preference: 'any',
    property_type: 'premium',
    room_types: ['Single Sharing', 'Double Sharing'],
    min_rent: 13000, max_rent: 23000,
    price_range: 'D11K / S20K',
    actual_pg_name: 'Urban Coliving',
    accessibility: ['Metro', 'Car Parking', 'Bike'],
    amenities: [...STD_AMENITIES, 'Study Area', 'Library'],
    usp: 'Near to Naruhalli metro',
    highlights: ['Near Metro', 'Library', 'Premium', 'No Curfew'],
    tier: 'Classics',
  }),

  pg({
    id: 'hood-coed', slug: 'hood-coed',
    name: 'Hood Luxe Coed Marathahalli', gharpayy_name: 'HOOD COED',
    area: 'Marathahalli', locality: 'Kundanhalli',
    nearby_landmarks: ['Marathahalli Market'],
    google_maps_url: 'https://maps.app.goo.gl/EkxZH5JPxmpuZbgs8',
    gender_preference: 'any',
    property_type: 'premium',
    noise_level: 'low',
    room_types: ['Pods Single', 'Twin Sharing', 'Studio Rooms', 'Single Rooms'],
    min_rent: 18000, max_rent: 38000,
    price_range: 'Pod18K / Twin22K / Single38K',
    food_type: 'veg',
    meals_included: 2,
    actual_pg_name: 'FF21 KDH',
    usp: 'Premium luxury property with pods',
    highlights: ['Premium Pods', 'Low Noise', 'Luxury Property', 'Near Marathahalli'],
    tier: 'Classics',
    average_rating: 4.9,
  }),

  pg({
    id: 'lexus-coed', slug: 'lexus-coed',
    name: 'Lexus Coed Marathahalli', gharpayy_name: 'LEXUS COED',
    area: 'Marathahalli', locality: 'Marathahalli',
    nearby_landmarks: ['Marathahalli Market'],
    gender_preference: 'any',
    property_type: 'premium',
    room_types: ['Pods Single Basic', 'Pods Single Deluxe', 'Pods Single Premium', 'Twin/Couple'],
    min_rent: 16000, max_rent: 38000,
    price_range: 'Pod-Basic16K / Pod-Deluxe19K / Pod-Premium20K / Twin36-38K',
    actual_pg_name: 'FF21 Pods Marathahalli',
    meals_included: 2,
    usp: 'Premium luxury property',
    highlights: ['Premium Pods', 'Luxury', 'Near Marathahalli', 'No Curfew'],
    tier: 'Classics',
  }),

  pg({
    id: 'maxx-coed', slug: 'maxx-coed',
    name: 'Maxx Coed Thubarahalli', gharpayy_name: 'MAXX COED',
    area: 'Marathahalli', locality: 'Thubarahalli',
    nearby_landmarks: ['Thubarahalli'],
    gender_preference: 'any',
    property_type: 'premium',
    room_types: ['Pods Single Basic', 'Pods Single Deluxe', 'Twin/Couple'],
    min_rent: 16000, max_rent: 38000,
    price_range: 'Pod-Basic16K / Pod-Deluxe19K / Twin36-38K',
    actual_pg_name: 'FF21 LIT Thubarahalli',
    food_type: 'veg',
    usp: 'Premium luxury property',
    highlights: ['Premium Pods', 'Luxury', 'Near Thubarahalli', 'No Curfew'],
    tier: 'Classics',
  }),

  pg({
    id: 'auxx-coed', slug: 'auxx-coed',
    name: 'Auxx Luxe Coed Mahadevapura', gharpayy_name: 'AUXX COED',
    area: 'Mahadevapura', locality: 'Mahadevapura',
    nearby_landmarks: ['Mahadevapura', 'Bagmane WTC'],
    gender_preference: 'any',
    property_type: 'premium',
    room_types: ['Single Sharing', 'Double Sharing'],
    min_rent: 18500, max_rent: 32000,
    price_range: 'D-Deluxe18.5K / D-Premium21K / S-Premium32K',
    actual_pg_name: 'FF21 PMC Mahadevapura',
    usp: 'Premium luxury stay',
    highlights: ['Premium Luxury', 'Near Bagmane', 'Fully Furnished', 'No Curfew'],
    tier: 'Classics',
  }),

  // ─── HSR LAYOUT ──────────────────────────────────────────────────────────
  pg({
    id: 'hs-metro-coed', slug: 'hs-metro-coed',
    name: 'HS Metro Coed HSR Layout', gharpayy_name: 'HS METRO COED',
    area: 'HSR Layout', locality: 'HSR Layout, Near Bommanahalli Metro',
    nearby_landmarks: ['HSR Layout Metro Station', 'Bommanahalli Metro'],
    google_maps_url: 'https://maps.app.goo.gl/x5b7KqMMoRACS369A',
    gender_preference: 'any',
    property_type: 'premium',
    room_types: ['Single Sharing', 'Double Sharing'],
    min_rent: 15000, max_rent: 29000,
    price_range: 'D-Exec15K / D-Deluxe16K / D-Suite17K / S-Exec25K / S-Deluxe26K / S-Suite27K',
    manager_contact: '7899700929',
    actual_pg_name: 'Sivani Coliving',
    accessibility: ['Metro', 'Bus', 'Bike'],
    meals_included: 3,
    food_type: 'both',
    usp: 'Near HSR metro, premium',
    highlights: ['Premium', 'Metro Access', 'HSR Layout', 'No Curfew'],
    tier: 'Classics',
  }),

  pg({
    id: 'hs-hugo-coed', slug: 'hs-hugo-coed',
    name: 'HS Hugo Coed HSR Layout', gharpayy_name: 'HS HUGO COED',
    area: 'HSR Layout', locality: 'HSR Layout, Near Hogasandra Metro',
    nearby_landmarks: ['Hogasandra Metro', 'HSR Layout'],
    google_maps_url: 'https://maps.app.goo.gl/52tJEDzbfbMvTDLF7',
    gender_preference: 'any',
    property_type: 'premium',
    noise_level: 'low',
    room_types: ['Single Sharing', 'Double Sharing'],
    min_rent: 15000, max_rent: 29000,
    price_range: 'D-Exec15K / D-Deluxe16K / D-Suite17K / S-Exec25K / S-Deluxe26K / S-Suite27K',
    manager_contact: '7899700929',
    actual_pg_name: 'Sivani Cherry Blossom',
    accessibility: ['Metro', 'Bus', 'Bike'],
    meals_included: 3,
    food_type: 'both',
    usp: 'Good locality',
    highlights: ['Premium', 'Low Noise', 'Metro Access', 'No Curfew'],
    tier: 'Classics',
  }),

  pg({
    id: 'hs-arq-coed', slug: 'hs-arq-coed',
    name: 'HS ARQ Coed HSR Layout', gharpayy_name: 'HS ARQ COED',
    area: 'HSR Layout', locality: 'HSR Layout',
    nearby_landmarks: ['HSR Layout'],
    gender_preference: 'any',
    property_type: 'premium',
    room_types: ['Single Sharing', 'Double Sharing', 'Suite'],
    min_rent: 15000, max_rent: 28000,
    price_range: 'D15K / Suite16K / S28K',
    manager_contact: '8978142139',
    actual_pg_name: 'Pro Coed',
    accessibility: ['Metro', 'Bus', 'Bike'],
    usp: 'Good near to Baker Street',
    highlights: ['Premium', 'Good Locality', 'Suite Rooms', 'No Curfew'],
    tier: 'Classics',
  }),

  pg({
    id: 'hs-edge-coed', slug: 'hs-edge-coed',
    name: 'HS Edge Coed HSR Layout', gharpayy_name: 'HS/EDGE COED',
    area: 'HSR Layout', locality: 'HSR Layout Metro Station',
    nearby_landmarks: ['HSR Layout Metro'],
    google_maps_url: 'https://maps.app.goo.gl/x5b7KqMMoRACS369A',
    gender_preference: 'any',
    property_type: 'premium',
    room_types: ['Single Sharing', 'Double Sharing'],
    min_rent: 13000, max_rent: 23000,
    price_range: 'D-Exec13K / S-Exec21K',
    manager_contact: '7899700929',
    actual_pg_name: 'Sivani Iris House',
    accessibility: ['Metro', 'Bus', 'Bike'],
    usp: 'Near HSR metro',
    highlights: ['Premium', 'Metro Access', 'Good Locality', 'No Curfew'],
    tier: 'Classics',
  }),

  pg({
    id: 'hs-affo-coed', slug: 'hs-affo-coed',
    name: 'HS Affo Coed HSR Layout', gharpayy_name: 'HS AFFO COED',
    area: 'HSR Layout', locality: 'HSR Layout, Kudulu',
    nearby_landmarks: ['HSR Layout'],
    google_maps_url: 'https://maps.app.goo.gl/SHyAe6cYg1a2jZbu9',
    gender_preference: 'any',
    property_type: 'budget',
    room_types: ['Single Sharing', 'Double Sharing'],
    min_rent: 10000, max_rent: 20000,
    price_range: 'D10K / S18K',
    actual_pg_name: 'Nesto Aloha Coliving PG',
    accessibility: ['Metro', 'Bus', 'Bike'],
    meals_included: 3,
    food_type: 'both',
    usp: 'Budget friendly',
    highlights: ['Budget Friendly', 'HSR Layout', 'Near Metro', 'No Curfew'],
    tier: 'Budget',
  }),

  pg({
    id: 'veluxe-coed', slug: 'veluxe-coed',
    name: 'VeLuxe Coed JP Nagar', gharpayy_name: 'VeLuxe COED',
    area: 'JP Nagar', locality: 'NS Palya, Near Vega City Mall',
    nearby_landmarks: ['Vega City Mall'],
    google_maps_url: 'https://maps.app.goo.gl/LGZV2Wd7mDqvqqPe6',
    gender_preference: 'any',
    property_type: 'premium',
    room_types: ['Single Sharing', 'Double Sharing'],
    min_rent: 14000, max_rent: 31000,
    price_range: 'D-Deluxe16K / D-Premium17K / S-Deluxe29K / S-Premium31K',
    manager_contact: '7899700929',
    actual_pg_name: 'Sivani Lotus',
    accessibility: ['Metro', 'Bus', 'Bike'],
    meals_included: 3,
    food_type: 'both',
    amenities: [...STD_AMENITIES, 'Rooftop Terrace'],
    usp: 'Premium locality',
    highlights: ['Premium', 'Vega City Mall', 'Rooftop', 'No Curfew'],
    tier: 'Classics',
  }),

  pg({
    id: 'vegas-coed', slug: 'vegas-coed',
    name: 'Vegas Coed JP Nagar', gharpayy_name: 'VEGAS COED',
    area: 'JP Nagar', locality: 'NS Palya, Near Vega City Mall',
    nearby_landmarks: ['Vega City Mall'],
    google_maps_url: 'https://maps.app.goo.gl/Cv2rVP3zUx3BBq7NA',
    gender_preference: 'any',
    property_type: 'premium',
    room_types: ['Single Sharing', 'Double Sharing'],
    min_rent: 13000, max_rent: 29000,
    price_range: 'D-Exec13K / D-Deluxe14K / D-Suite15K / S-Exec25K / S-Deluxe26K / S-Suite27K',
    manager_contact: '7899700929',
    actual_pg_name: 'Orchid House Vegas Coed',
    accessibility: ['Metro', 'Bus', 'Bike'],
    meals_included: 3,
    food_type: 'both',
    amenities: [...STD_AMENITIES, 'Gym', 'Study Area'],
    usp: 'Premium locality',
    highlights: ['Premium', 'Near Vega City', 'Gym & Study', 'No Curfew'],
    tier: 'Classics',
  }),

  // ─── JAYANAGAR ───────────────────────────────────────────────────────────
  pg({
    id: 'luna-girls', slug: 'luna-girls',
    name: 'Luna Girls Jayanagar', gharpayy_name: 'LUNA GIRLS',
    area: 'Jayanagar', locality: 'Jayanagar',
    nearby_landmarks: ['Jayanagar'],
    google_maps_url: 'https://maps.app.goo.gl/x7frvw1knt4JgM4y9',
    gender_preference: 'female',
    room_types: ['Single Sharing', 'Double Sharing', 'Triple Sharing'],
    min_rent: 16000, max_rent: 31000,
    price_range: 'T16K / D19K / S31K',
    manager_contact: '7416687752',
    owner_contact: '7411911136',
    actual_pg_name: 'Sakshi Living Ladies PG Jayanagar',
    accessibility: ['Metro'],
    meals_included: 3,
    usp: 'Great property, games, very nearby to offices',
    highlights: ['Girls Only', 'Jayanagar', 'Metro Access', 'No Curfew'],
    tier: 'Mid',
  }),

  // ─── MG ROAD / VASANTH NAGAR ─────────────────────────────────────────────
  pg({
    id: 'velvet-girls', slug: 'velvet-girls',
    name: 'Velvet Girls MG Road', gharpayy_name: 'VELVET GIRLS',
    area: 'MG Road', locality: 'Vasanth Nagar, MG Road',
    nearby_landmarks: ['MG Road'],
    gender_preference: 'female',
    room_types: ['Single Sharing', 'Double Sharing', 'Triple Sharing'],
    min_rent: 10000, max_rent: 24000,
    price_range: 'T10K / D14K / S24K',
    owner_contact: '8088303270',
    actual_pg_name: 'Hive Living',
    accessibility: ['Metro', 'Bus'],
    usp: 'Budget friendly, games, coliving',
    highlights: ['Girls Only', 'MG Road Area', 'Metro Access', 'No Curfew'],
    tier: 'Mid',
  }),

  pg({
    id: 'queens-mcc-girls', slug: 'queens-mcc-girls',
    name: "Queen's MCC Girls Vasanth Nagar", gharpayy_name: "QUEEN'S MCC GIRLS",
    area: 'MG Road', locality: 'Vasanth Nagar',
    nearby_landmarks: ['MG Road'],
    google_maps_url: 'https://maps.app.goo.gl/3e2CEGKgS7ZRpMLV8',
    gender_preference: 'female',
    property_type: 'premium',
    room_types: ['Single Sharing', 'Double Sharing', 'Triple Sharing', 'Four Sharing'],
    min_rent: 12500, max_rent: 20000,
    price_range: '4-Sharing12.5K / T14-15K / D18-20K',
    food_type: 'veg',
    manager_contact: '6363901319',
    owner_contact: '9108895879',
    actual_pg_name: 'Adler Stays Vasanth Nagar',
    accessibility: ['Metro', 'Bus'],
    meals_included: 4,
    usp: 'New built, premium property',
    highlights: ['Girls Only', 'Premium', 'Near MG Road', '4 Meals/Day'],
    tier: 'Classics',
  }),

  // ─── INDIRANAGAR ─────────────────────────────────────────────────────────
  pg({
    id: 'dom-girls', slug: 'dom-girls',
    name: 'Dom Girls Indiranagar', gharpayy_name: 'Dom girls',
    area: 'Indiranagar', locality: 'Domlur, Indiranagar',
    nearby_landmarks: ['Indiranagar'],
    google_maps_url: 'https://maps.app.goo.gl/ubgUxqMaBY6vFqa66',
    gender_preference: 'female',
    room_types: ['Single Sharing', 'Double Sharing'],
    min_rent: 12000, max_rent: 21000,
    price_range: 'D12K / S21K',
    manager_contact: 'Kishore',
    actual_pg_name: 'Arcade Inn',
    accessibility: ['Metro', 'Bus'],
    usp: 'Newest PG, Prime Location, WFH Enabler, Food Good',
    highlights: ['Girls Only', 'Near Indiranagar Metro', 'WFH Friendly', 'No Curfew'],
    tier: 'Mid',
  }),

  // ─── CHRIST UNIVERSITY / YESHWANTHPUR ───────────────────────────────────
  pg({
    id: 'fort-boys', slug: 'fort-boys',
    name: 'Fort Boys Christ Yeshwanthpur', gharpayy_name: 'FORT BOYS',
    area: 'Yeshwanthpur', locality: 'Near Christ University Yeshwanthpur Campus',
    nearby_landmarks: ['Christ University Yeshwanthpur Campus'],
    google_maps_url: 'https://maps.app.goo.gl/2i8xYsTyaY2NEJNe9',
    gender_preference: 'male',
    room_types: ['Double Sharing'],
    min_rent: 17000, max_rent: 17000,
    price_range: 'D17K',
    meals_included: 4,
    actual_pg_name: 'Puzzles Bravado',
    accessibility: ['Metro', 'Bus'],
    usp: '450m from campus',
    highlights: ['Boys Only', '450m from Campus', '4 Meals/Day', 'No Curfew'],
    tier: 'Mid',
  }),

  pg({
    id: 'paradise-girls', slug: 'paradise-girls',
    name: 'Paradise Girls Christ Yeshwanthpur', gharpayy_name: 'paradise girls',
    area: 'Yeshwanthpur', locality: 'Near Christ University Yeshwanthpur Campus',
    nearby_landmarks: ['Christ University Yeshwanthpur Campus'],
    google_maps_url: 'https://maps.app.goo.gl/2i8xYsTyaY2NEJNe9',
    gender_preference: 'female',
    room_types: ['Double Sharing', 'Triple Sharing'],
    min_rent: 17000, max_rent: 20000,
    price_range: 'T17K / D20K',
    meals_included: 4,
    manager_contact: '9686025547',
    actual_pg_name: 'Best Girls ADL',
    accessibility: ['Metro', 'Bus'],
    usp: '350m from campus',
    highlights: ['Girls Only', '350m from Campus', '4 Meals/Day', 'No Curfew'],
    tier: 'Mid',
  }),

  pg({
    id: 'wise-boys', slug: 'wise-boys',
    name: 'Wise Boys Christ Yeshwanthpur', gharpayy_name: 'Wise boys',
    area: 'Yeshwanthpur', locality: 'Near Christ University Yeshwanthpur Campus',
    nearby_landmarks: ['Christ University Yeshwanthpur Campus'],
    google_maps_url: 'https://maps.app.goo.gl/2i8xYsTyaY2NEJNe9',
    gender_preference: 'male',
    room_types: ['Single Sharing', 'Double Sharing'],
    min_rent: 14000, max_rent: 23000,
    price_range: 'D14K / S23K',
    meals_included: 4,
    manager_contact: '8217863474',
    actual_pg_name: '900 MTR Adler Boys',
    accessibility: ['Metro', 'Bus'],
    usp: '750m from campus',
    highlights: ['Boys Only', '750m from Campus', '4 Meals/Day', 'No Curfew'],
    tier: 'Mid',
  }),

  // ─── MYNT / MISC ─────────────────────────────────────────────────────────
  pg({
    id: 'mynt-coed', slug: 'mynt-coed',
    name: 'Mynt Coed Bellandur/Myntra', gharpayy_name: 'MYNT COED',
    area: 'Bellandur', locality: 'Bellandur, Near Myntra Office',
    nearby_landmarks: ['Myntra Office', 'Bellandur'],
    google_maps_url: 'https://maps.app.goo.gl/dZESHUqvxvXkr4a56',
    gender_preference: 'any',
    room_types: ['Single Sharing', 'Double Sharing'],
    min_rent: 13000, max_rent: 24000,
    price_range: 'D11K / S21K',
    actual_pg_name: 'Urban Coliving',
    accessibility: ['Bus', 'Bike'],
    meals_included: 3,
    food_type: 'both',
    usp: 'Near to Myntra office',
    highlights: ['Near Myntra', 'Office Area', 'Gym', 'No Curfew'],
    tier: 'Mid',
  }),

  pg({
    id: 'tove-boys', slug: 'tove-boys',
    name: 'Tove Boys Koramangala', gharpayy_name: 'TOVE BOYS',
    area: 'Koramangala', locality: 'SG Palya',
    nearby_landmarks: ['Nexus Mall', 'Christ University'],
    gender_preference: 'male',
    property_type: 'budget',
    room_types: ['Single Sharing', 'Double Sharing', 'Triple Sharing'],
    min_rent: 8000, max_rent: 18000,
    price_range: 'T7.5K / D11K / S17K',
    manager_contact: '7294828337',
    actual_pg_name: 'Sapthagiri PG',
    usp: 'Budget friendly',
    highlights: ['Boys Only', 'Budget', 'SG Palya', 'No Curfew'],
    tier: 'Budget',
  }),

  pg({
    id: 'khb-boys', slug: 'khb-boys',
    name: 'KHB Boys Koramangala', gharpayy_name: 'KHB BOYS',
    area: 'Koramangala', locality: 'SG Palya',
    nearby_landmarks: ['Nexus Mall', 'Christ University'],
    gender_preference: 'male',
    room_types: ['Single Sharing', 'Double Sharing', 'Triple Sharing'],
    min_rent: 10000, max_rent: 21000,
    price_range: 'T8K / D12K / S18K',
    manager_contact: '8999972220',
    owner_contact: '9160689366',
    actual_pg_name: 'Sri Varahi',
    usp: 'Budget friendly',
    highlights: ['Boys Only', 'Budget Friendly', 'SG Palya', 'No Curfew'],
    tier: 'Mid',
  }),

  pg({
    id: 'jazz-coed', slug: 'jazz-coed',
    name: 'Jazz Coed Koramangala', gharpayy_name: 'Jazz coed',
    area: 'Koramangala', locality: 'SG Palya, Dairy Circle',
    nearby_landmarks: ['Nexus Mall', 'Christ University', 'Dairy Circle'],
    gender_preference: 'any',
    room_types: ['Single Sharing', 'Double Sharing'],
    min_rent: 16000, max_rent: 29000,
    price_range: 'D16K / S29K',
    meals_included: 4,
    food_type: 'veg',
    actual_pg_name: 'Atlas Coliving PG',
    amenities: [...STD_AMENITIES, 'Study Area', 'Parking'],
    usp: 'Coliving, no curfew',
    highlights: ['Co-ed', '4 Meals/Day', 'Coliving', 'No Curfew'],
    tier: 'Mid',
  }),

  pg({
    id: 'byg-coed', slug: 'byg-coed',
    name: 'BYG Coed Koramangala', gharpayy_name: 'byg coed',
    area: 'Koramangala', locality: 'Silk Board, SG Palya, MG Road',
    nearby_landmarks: ['Nexus Mall', 'Christ University', 'Dairy Circle'],
    gender_preference: 'any',
    room_types: ['Single Sharing', 'Double Sharing'],
    min_rent: 13000, max_rent: 25000,
    price_range: 'D13K / S25K',
    food_type: 'veg',
    manager_contact: '7337433078',
    actual_pg_name: 'Siva Malleswari Coliving',
    usp: 'Newest PG, Prime Location, WFH Enabler, Food Good',
    highlights: ['Co-ed', 'Prime Location', 'WFH Friendly', 'No Curfew'],
    tier: 'Mid',
  }),

  pg({
    id: 'elite-coed', slug: 'elite-coed',
    name: 'Elite Coed Koramangala', gharpayy_name: 'elite COED',
    area: 'Koramangala', locality: 'Silk Board, SG Palya, MG Road',
    nearby_landmarks: ['Nexus Mall', 'Christ University', 'Dairy Circle'],
    gender_preference: 'any',
    room_types: ['Single Sharing', 'Double Sharing', 'Triple Sharing'],
    min_rent: 10000, max_rent: 21000,
    price_range: 'T10K / D14K / S21K',
    food_type: 'veg',
    manager_contact: '8217411288',
    group_name: 'KLP',
    actual_pg_name: 'Kalpavriksha 5 New',
    usp: 'Newest PG, Prime Location, WFH Enabler, Food Good',
    highlights: ['Co-ed', 'Prime Location', 'WFH Enabler', 'No Curfew'],
    tier: 'Mid',
  }),

  pg({
    id: 'korve-coed-k', slug: 'korve-coed-k',
    name: 'Korve Coed Koramangala (Near Nextt Door)', gharpayy_name: 'KORVE COED',
    area: 'Koramangala', locality: 'Koramangala',
    nearby_landmarks: ['Nexus Mall', 'Christ University'],
    gender_preference: 'any',
    property_type: 'premium',
    room_types: ['Single Sharing', 'Double Sharing'],
    min_rent: 18000, max_rent: 35000,
    price_range: 'D-Classic18K / D-Premium22K / S-Classic28K / S-Premium35K',
    manager_contact: '8139991234',
    owner_contact: '9701848769',
    actual_pg_name: 'Nextt Door',
    usp: 'Premium property',
    highlights: ['Premium', 'Koramangala', 'No Curfew', 'Fully Furnished'],
    tier: 'Classics',
  }),
];

// Derive KORAMANGALA_PROPERTIES for backward compat
export const KORAMANGALA_PROPERTIES = ALL_PROPERTIES.filter(
  p => p.area === 'Koramangala'
);

// Helper: get properties by area
export function getPropertiesByArea(area: string): PGProperty[] {
  return ALL_PROPERTIES.filter(
    p => p.area.toLowerCase().includes(area.toLowerCase()) ||
         p.locality.toLowerCase().includes(area.toLowerCase())
  );
}

// Helper: search properties
export function searchProperties(opts: {
  area?: string;
  gender?: 'male' | 'female' | 'any';
  maxRent?: number;
  propertyType?: string;
  foodType?: string;
}): PGProperty[] {
  let results = [...ALL_PROPERTIES];
  if (opts.area) {
    results = results.filter(p =>
      p.area.toLowerCase().includes(opts.area!.toLowerCase()) ||
      p.locality.toLowerCase().includes(opts.area!.toLowerCase()) ||
      p.city.toLowerCase().includes(opts.area!.toLowerCase())
    );
  }
  if (opts.gender && opts.gender !== 'any') {
    results = results.filter(p => p.gender_preference === opts.gender || p.gender_preference === 'any');
  }
  if (opts.maxRent) {
    results = results.filter(p => p.min_rent <= opts.maxRent!);
  }
  if (opts.propertyType) {
    results = results.filter(p => p.property_type === opts.propertyType);
  }
  if (opts.foodType) {
    results = results.filter(p => p.food_type === opts.foodType || p.food_type === 'both');
  }
  return results;
}

// All unique areas
export const ALL_AREAS = [...new Set(ALL_PROPERTIES.map(p => p.area))];

// Stats
export const PROPERTY_STATS = {
  total: ALL_PROPERTIES.length,
  koramangala: KORAMANGALA_PROPERTIES.length,
  girls: ALL_PROPERTIES.filter(p => p.gender_preference === 'female').length,
  boys: ALL_PROPERTIES.filter(p => p.gender_preference === 'male').length,
  coed: ALL_PROPERTIES.filter(p => p.gender_preference === 'any').length,
  premium: ALL_PROPERTIES.filter(p => p.property_type === 'premium').length,
  budget: ALL_PROPERTIES.filter(p => p.property_type === 'budget').length,
};
